#!/bin/zsh
# Edge-case checks: the ways Doppel used to go wrong when something about the
# request was unusual — a mistyped colour, two names that collide, a path
# already occupied, data an instance does not own.
#
# Every assertion here comes from a failure found by driving the real tool.
# Cheap cases run against a throwaway DOPPEL_HOME with nothing installed; the
# ones that need a real bundle share a single instance and clean it up.
#
#   qa/edge.zsh [--cli /path/to/doppel]

set -u
setopt PIPE_FAIL

readonly REPO_ROOT="${0:A:h:h}"
CLI="$REPO_ROOT/bin/doppel"
[[ "${1:-}" == "--cli" ]] && CLI="$2"

readonly PRIMARY="${DOPPEL_PRIMARY_APP:-/Applications/ChatGPT.app}"
readonly SCRATCH="$(/usr/bin/mktemp -d "${TMPDIR:-/tmp}/doppel-edge.XXXXXXXX")"
readonly DOPPEL_DIR="$HOME/Library/Application Support/Doppel"
readonly NAME="Doppel Edge $$"
readonly SLUG="$(print -r -- "$NAME" | /usr/bin/tr '[:upper:]' '[:lower:]' | /usr/bin/sed -E 's/[^a-z0-9]+/-/g; s/^-+|-+$//g')"
readonly SIBLING_SLUG="doppel-edge-sibling-$$"
readonly SIBLING_NAME="Doppel Edge Sibling $$"
readonly APPS="$SCRATCH/Applications"
export DOPPEL_RELAUNCH=0

typeset -i PASSED=0 FAILED=0
pass() { print -r -- "  ✓ $1"; (( PASSED += 1 )); return 0 }
fail() { print -r -- "  ✗ $1"; print -r -- "      $2"; (( FAILED += 1 )); return 0 }
check() {
    if [[ "$2" == "$3" ]]; then pass "$1"; else fail "$1" "expected '$3', got '$2'"; fi
}

typeset OUT="" STATUS=0
run_isolated() {
    local home="$SCRATCH/$1"; shift
    OUT="$(DOPPEL_HOME="$home" "$CLI" "$@" 2>&1)"
    STATUS=$?
    return 0
}
run_real() {
    OUT="$("$CLI" "$@" 2>&1)"
    STATUS=$?
    return 0
}

config_field() { ( source "$1/instance-config.zsh" 2>/dev/null || true; print -r -- "${(P)2:-}" ) }

# Rewrites a config the way the CLI writes it, so a value with spaces in it is
# escaped exactly as the real thing would escape it.
write_config_file() {
    local dir="$1" name="$2" id="$3" scheme="$4" profile="$5" codex="$6" tint="$7"
    {
        print -r -- "# Doppel instance config. Generated by doppel; do not hand-edit quoting."
        printf 'DOPPEL_DISPLAY_NAME=%q\n' "$name"
        printf 'DOPPEL_BUNDLE_ID=%q\n' "$id"
        printf 'DOPPEL_URL_SCHEME=%q\n' "$scheme"
        printf 'DOPPEL_PROFILE_ROOT=%q\n' "$profile"
        printf 'DOPPEL_CODEX_HOME=%q\n' "$codex"
        printf 'DOPPEL_TINT=%q\n' "$tint"
    } > "$dir/instance-config.zsh"
}

set_profile_root() {
    local dir="$1"
    write_config_file "$dir" \
        "$(config_field "$dir" DOPPEL_DISPLAY_NAME)" \
        "$(config_field "$dir" DOPPEL_BUNDLE_ID)" \
        "$(config_field "$dir" DOPPEL_URL_SCHEME)" \
        "$2" \
        "$(config_field "$dir" DOPPEL_CODEX_HOME)" \
        "$(config_field "$dir" DOPPEL_TINT)"
}

# Where the CLI currently thinks this instance's app lives. Re-read rather than
# remembered: a rename moves it.
app_path() { "$CLI" list --porcelain | /usr/bin/awk -F'\t' -v s="$SLUG" '$1 == s {print $3}' }
pin_file() {
    print -r -- "$DOPPEL_DIR/pins/$(print -rn -- "${1:A}" | /usr/bin/shasum -a 256 | /usr/bin/awk '{print $1}')"
}

cleanup() {
    local final
    final="$(app_path)"
    # Without --purge-data: the throwaway profile lives under $TMPDIR, and
    # purging refuses anything outside the home directory by design.
    "$CLI" remove "$(config_field "$DOPPEL_DIR/instances/$SLUG" DOPPEL_DISPLAY_NAME)" >/dev/null 2>&1 || true
    /bin/rm -rf "$DOPPEL_DIR/instances/$SLUG" 2>/dev/null || true
    /bin/rm -rf "$DOPPEL_DIR/instances/$SIBLING_SLUG" 2>/dev/null || true
    /bin/rm -rf "$DOPPEL_DIR/state/Removed/$SLUG."*(N) 2>/dev/null || true
    /bin/rm -rf "$DOPPEL_DIR/state/com.openai.codex.doppel-$SLUG" 2>/dev/null || true
    [[ -n "$final" ]] && /bin/rm -f "$(pin_file "$final")" 2>/dev/null
    /bin/rm -rf "$SCRATCH" 2>/dev/null || true
    return 0
}
trap cleanup EXIT

[[ -d "$PRIMARY" ]] || { print -u2 -r -- "the primary app is required at $PRIMARY"; exit 1 }
/bin/mkdir -p "$APPS"

print -r -- "Doppel edge cases"
print -r -- "  cli: $CLI"
print -r -- ""

print -r -- "a create that fails leaves nothing behind to trip over"
run_isolated tint create --name "Bad Hex" --tint ZZZZZZ --install-to "$APPS"
(( STATUS != 0 )) && pass "a mistyped colour is refused" || fail "a mistyped colour is refused" "exited 0"
[[ ! -d "$SCRATCH/tint/instances/bad-hex" ]] && pass "no half-built instance directory" \
    || fail "no half-built instance directory" "$SCRATCH/tint/instances/bad-hex survived"
run_isolated icon create --name "No Icon" --icon /nope/missing.icns --install-to "$APPS"
[[ "$OUT" == *"no icon file at"* ]] && pass "a missing --icon file is explained" \
    || fail "a missing --icon file is explained" "got: $OUT"
[[ ! -d "$SCRATCH/icon/instances/no-icon" ]] && pass "and leaves no directory either" \
    || fail "and leaves no directory either" "$SCRATCH/icon/instances/no-icon survived"

print -r -- ""
print -r -- "URL scheme ownership is case-insensitive"
run_isolated scheme-primary create --name "Primary Scheme" --tint 3B82F6 \
    --scheme CoDeX --install-to "$APPS"
[[ "$OUT" == *"belongs to the primary app"* ]] \
    && pass "a case variant cannot claim the primary callback" \
    || fail "a case variant cannot claim the primary callback" "got: $OUT"
/bin/mkdir -p "$SCRATCH/scheme-duplicate/instances/existing"
write_config_file "$SCRATCH/scheme-duplicate/instances/existing" "Existing" \
    "com.example.existing" "codex-shared" "$SCRATCH/existing-profile" \
    "$SCRATCH/existing-codex" "3B82F6"
run_isolated scheme-duplicate create --name "Duplicate Scheme" --tint EF4444 \
    --scheme CODEX-SHARED --install-to "$APPS"
[[ "$OUT" == *"already used by instance 'existing'"* ]] \
    && pass "case variants cannot collide between instances" \
    || fail "case variants cannot collide between instances" "got: $OUT"
ENGINE_SCHEME_DIR="$SCRATCH/engine-scheme"
/bin/mkdir -p "$ENGINE_SCHEME_DIR"
write_config_file "$ENGINE_SCHEME_DIR" "Legacy Scheme" "com.example.legacy-scheme" \
    "cOdEx" "$SCRATCH/legacy-profile" "$SCRATCH/legacy-codex" "3B82F6"
OUT="$(DOPPEL_NO_ALERT=1 DOPPEL_ASSET_ROOT="$ENGINE_SCHEME_DIR" \
    /bin/zsh "$REPO_ROOT/engine/doppel-engine.zsh" install \
    "$SCRATCH/Legacy Scheme.app" 2>&1)"
STATUS=$?
[[ "$OUT" == *"instance URL scheme belongs to the primary app"* ]] \
    && pass "an existing case-variant config fails closed before rebuild" \
    || fail "an existing case-variant config fails closed before rebuild" \
        "got status $STATUS, output: $OUT"

print -r -- ""
print -r -- "a directory without a config does not take every command down with it"
/bin/mkdir -p "$SCRATCH/broken/instances/wreckage"
run_isolated broken list --porcelain
check "list still succeeds" "$STATUS" "0"
[[ -z "$OUT" ]] && pass "and simply ignores it" || fail "and simply ignores it" "printed: $OUT"
run_isolated broken remove "Anything"
[[ "$OUT" == *"no instance named"* ]] && pass "remove says what is wrong" \
    || fail "remove says what is wrong" "got status $STATUS, output: '$OUT'"

print -r -- ""
print -r -- "an empty field in a runtime snapshot does not shift the ones after it"
# The unmanaged and ambiguous rows carry no slug. `read` used to lose that
# empty field, because tab is an IFS whitespace character in zsh and runs of
# them collapse, so the process ID slid into the name and the menu offered to
# assign a built-in browser profile called "701". Only the parsing is driven
# here; which row gets built needs live ChatGPT processes.
snapshot_fields() {
    SNAPSHOT_CLI="$CLI" SNAPSHOT_ROW="$1" /bin/zsh -c '
        body="$(/usr/bin/sed -n "/^parse_vendor_runtime_snapshot() {/,/^}/p" "$SNAPSHOT_CLI")"
        # Without this the extraction failing reads as four mismatched fields
        # rather than as a renamed or reindented function.
        [[ -n "$body" ]] || {
            print -r -- "parse_vendor_runtime_snapshot not found in $SNAPSHOT_CLI"
            exit 0
        }
        eval "$body"
        local runtime_kind runtime_slug runtime_name runtime_pid
        parse_vendor_runtime_snapshot "$SNAPSHOT_ROW"
        print -r -- "$runtime_kind|$runtime_slug|$runtime_name|$runtime_pid"
    '
}
check "an unmanaged row names the app rather than its PID" \
    "$(snapshot_fields "$(printf 'unmanaged\t\tChatGPT\t701')")" "unmanaged||ChatGPT|701"
check "an ambiguous row keeps its names apart from its PIDs" \
    "$(snapshot_fields "$(printf 'ambiguous\t\tOne, Two\t12 34')")" "ambiguous||One, Two|12 34"
check "a managed row still carries its slug" \
    "$(snapshot_fields "$(printf 'managed\tslug-a\tName A\t99')")" "managed|slug-a|Name A|99"
check "no official process at all reads as none" \
    "$(snapshot_fields none)" "none|||"

print -r -- ""
print -r -- "quitting an instance takes its helper processes with it"
# Electron's crashpad handlers and the modifier monitor live under Frameworks
# and Resources, not Contents/MacOS, so the graceful quit never covered them.
# They outlived every remove and rebuild, and moving the bundle afterwards left
# them pointing at a path that no longer existed.
HELPER_APP="$SCRATCH/Helpers Live.app"
/bin/mkdir -p "$HELPER_APP/Contents/MacOS" \
    "$HELPER_APP/Contents/Frameworks/Codex Framework.framework/Helpers" \
    "$HELPER_APP/Contents/Resources/native"
/bin/ln -sf /bin/sleep "$HELPER_APP/Contents/Frameworks/Codex Framework.framework/Helpers/browser_crashpad_handler"
/bin/ln -sf /bin/sleep "$HELPER_APP/Contents/Resources/native/bare-modifier-monitor"
/bin/mkdir -p "$HELPER_APP/Contents/Frameworks/Sparkle.framework/Versions/B" \
    "$HELPER_APP/Contents/Resources/cua_node/bin"
/bin/ln -sf /bin/sleep "$HELPER_APP/Contents/Frameworks/Sparkle.framework/Versions/B/Autoupdate"
/bin/ln -sf /bin/sleep "$HELPER_APP/Contents/Resources/cua_node/bin/node"
"$HELPER_APP/Contents/Frameworks/Codex Framework.framework/Helpers/browser_crashpad_handler" 300 &
CRASHPAD_PID=$!
"$HELPER_APP/Contents/Resources/native/bare-modifier-monitor" 300 &
MONITOR_PID=$!
# Sparkle's updater is detached on purpose so it can outlive the app it is
# updating, and the Computer Use node server sits elsewhere under Resources.
# Sweeping the whole bundle took both, which on the stock ChatGPT app threw
# away a staged vendor update for nothing.
"$HELPER_APP/Contents/Frameworks/Sparkle.framework/Versions/B/Autoupdate" 300 &
SPARKLE_PID=$!
"$HELPER_APP/Contents/Resources/cua_node/bin/node" 300 &
CUA_PID=$!
/bin/sleep 1
# The app itself is already gone, which is precisely the state that stranded
# them: quit_instance saw nothing under Contents/MacOS and returned happy.
HELPERS_BEFORE=0
/bin/kill -0 "$CRASHPAD_PID" 2>/dev/null && (( HELPERS_BEFORE += 1 ))
/bin/kill -0 "$MONITOR_PID" 2>/dev/null && (( HELPERS_BEFORE += 1 ))
check "both helpers are running to begin with" "$HELPERS_BEFORE" "2"
REAP_FUNCS='/^reapable_bundle_path() {/,/^}/p;/^bundle_pids() {/,/^}/p'
REAP_FUNCS="$REAP_FUNCS;/^bundle_app_is_running() {/,/^}/p"
REAP_FUNCS="$REAP_FUNCS;/^reap_bundle_processes() {/,/^}/p;/^quit_instance() {/,/^}/p"
SNAPSHOT_CLI="$CLI" HELPER_APP="$HELPER_APP" REAP_FUNCS="$REAP_FUNCS" /bin/zsh -c '
    body="$(/usr/bin/sed -n "$REAP_FUNCS" "$SNAPSHOT_CLI")"
    [[ -n "$body" ]] || { print -r -- "quit_instance not found in $SNAPSHOT_CLI"; exit 1 }
    die() { print -u2 -r -- "die: $*"; exit 1 }
    eval "$body"
    quit_instance "$HELPER_APP" "com.example.helpers-live" "Helpers Live"
' >/dev/null 2>&1
HELPERS_AFTER=0
/bin/kill -0 "$CRASHPAD_PID" 2>/dev/null && (( HELPERS_AFTER += 1 ))
/bin/kill -0 "$MONITOR_PID" 2>/dev/null && (( HELPERS_AFTER += 1 ))
check "and none survive the quit" "$HELPERS_AFTER" "0"
SURVIVORS=0
/bin/kill -0 "$SPARKLE_PID" 2>/dev/null && (( SURVIVORS += 1 ))
/bin/kill -0 "$CUA_PID" 2>/dev/null && (( SURVIVORS += 1 ))
check "but the detached updater and the node server are left alone" "$SURVIVORS" "2"
/bin/kill -9 "$CRASHPAD_PID" "$MONITOR_PID" "$SPARKLE_PID" "$CUA_PID" 2>/dev/null || true

# A bundle path that is empty or not an app would turn the prefix match into
# "/", which is every process on the machine. The sweep has to refuse rather
# than signal anything at all.
/bin/sleep 300 &
BYSTANDER_PID=$!
REAP_REFUSED="$(SNAPSHOT_CLI="$CLI" REAP_FUNCS="$REAP_FUNCS" /bin/zsh -c '
    set -u
    body="$(/usr/bin/sed -n "$REAP_FUNCS" "$SNAPSHOT_CLI")"
    [[ -n "$body" ]] || { print -r -- "missing"; exit 0 }
    eval "$body"
    # Anything printed to stderr here means the sweep errored rather than
    # refusing, which would make this check pass for the wrong reason.
    for bad in "" "/" "/Users" "relative.app" "/tmp/../.app"; do
        reap_bundle_processes "$bad" 2>&1 >/dev/null | /usr/bin/grep -q . && \
            { print -r -- "errored on [$bad]"; exit 0 }
    done
    print -r -- "refused"
')"
/bin/sleep 1
check "a sweep of a non-bundle path signals nothing" \
    "$([[ "$REAP_REFUSED" == "refused" ]] && /bin/kill -0 "$BYSTANDER_PID" 2>/dev/null && print safe || print unsafe)" \
    "safe"
/bin/kill -9 "$BYSTANDER_PID" 2>/dev/null || true

# The running check and the sweep have to agree about what "running" means.
# `pgrep -f` reads its argument as a regular expression, so an install root
# holding regex punctuation made it miss a live app. That mattered once the
# sweep existed: the graceful quit was skipped and the app was signalled
# instead of asked, taking the dialog-open refusal with it.
META_APP="$SCRATCH/Applications (Work)/Meta+Bundle [1].app"
/bin/mkdir -p "$META_APP/Contents/MacOS"
/bin/ln -sf /bin/sleep "$META_APP/Contents/MacOS/ChatGPT"
"$META_APP/Contents/MacOS/ChatGPT" 300 &
META_PID=$!
/bin/sleep 1
check "pgrep -f misses a bundle path holding regex punctuation" \
    "$(/usr/bin/pgrep -f "$META_APP/Contents/MacOS/" >/dev/null 2>&1 && print found || print missed)" \
    "missed"
check "the literal matcher finds it" \
    "$(SNAPSHOT_CLI="$CLI" META_APP="$META_APP" REAP_FUNCS="$REAP_FUNCS" /bin/zsh -c '
        eval "$(/usr/bin/sed -n "$REAP_FUNCS" "$SNAPSHOT_CLI")"
        bundle_app_is_running "$META_APP" && print found || print missed')" \
    "found"
/bin/kill -9 "$META_PID" 2>/dev/null || true

print -r -- ""
print -r -- "an instance's cache is purged with the rest of its data"
cache_for() {
    SNAPSHOT_CLI="$CLI" PROFILE_ROOT="$1" /bin/zsh -c '
        body="$(/usr/bin/sed -n "/^instance_cache_path() {/,/^}/p" "$SNAPSHOT_CLI")"
        [[ -n "$body" ]] || { print -r -- "instance_cache_path not found in $SNAPSHOT_CLI"; exit 1 }
        eval "$body"
        instance_cache_path "$PROFILE_ROOT"
    '
}
check "a profile under Application Support has a matching cache" \
    "$(cache_for "$HOME/Library/Application Support/Doppel QA 1")" \
    "$HOME/Library/Caches/Doppel QA 1"
check "a nested profile keeps its shape" \
    "$(cache_for "$HOME/Library/Application Support/Vendor/Nested")" \
    "$HOME/Library/Caches/Vendor/Nested"
check "a profile kept elsewhere has no separate cache" \
    "$(cache_for "$SCRATCH/somewhere-else")" ""
# The stock app's own cache has to be as untouchable as its profile, or an
# instance pointed at the primary's profile root would purge the primary's
# cache along with it. Veridue is pointed exactly there on this machine.
PRIMARY_CACHE_GUARDED="$(SNAPSHOT_CLI="$CLI" PRIMARY_APP="$PRIMARY" /bin/zsh -c '
    body="$(/usr/bin/sed -n "/^primary_data_paths() {/,/^}/p" "$SNAPSHOT_CLI")"
    [[ -n "$body" ]] || { print -r -- "primary_data_paths not found in $SNAPSHOT_CLI"; exit 1 }
    eval "$body"
    primary_data_paths | /usr/bin/grep -c "Library/Caches/" || true
')"
check "the primary's cache is guarded, not just its profile" \
    "$([[ "${PRIMARY_CACHE_GUARDED:-0}" -ge 1 ]] && print yes || print no)" "yes"

print -r -- ""
print -r -- "a name resolves to the instance that carries it, not to the one whose"
print -r -- "directory happens to be spelled the same way"
# Two definitions whose names differ but whose identifiers would match. The
# guard above stops these being created now; a config written before it exists
# still has to resolve to the right instance rather than to its neighbour.
/bin/mkdir -p "$SCRATCH/shadow/instances/alpha" "$SCRATCH/shadow/instances/beta"
write_config_file "$SCRATCH/shadow/instances/alpha" "Alpha One" \
    "com.example.alpha" "codex-alpha" "$SCRATCH/alpha" "$SCRATCH/alpha-codex" "EF4444"
write_config_file "$SCRATCH/shadow/instances/beta" "Alpha-One" \
    "com.example.beta" "codex-beta" "$SCRATCH/beta" "$SCRATCH/beta-codex" "3B82F6"
run_isolated shadow launch "Alpha-One"
[[ "$OUT" == *"Alpha-One.app"* ]] && pass "'Alpha-One' resolves to the instance called Alpha-One" \
    || fail "'Alpha-One' resolves to the instance called Alpha-One" "got: $OUT"
run_isolated shadow launch "Alpha One"
[[ "$OUT" == *"Alpha One.app"* ]] && pass "'Alpha One' still resolves to Alpha One" \
    || fail "'Alpha One' still resolves to Alpha One" "got: $OUT"

print -r -- ""
print -r -- "an occupied path is refused rather than quietly taken over"
/bin/mkdir -p "$APPS/Occupied.app/Contents"
print -r -- "not Doppel's" > "$APPS/Occupied.app/Contents/marker"
run_isolated occupied create --name "Occupied" --tint 3B82F6 --install-to "$APPS"
[[ "$OUT" == *"an app already exists"* ]] && pass "create refuses an occupied app path" \
    || fail "create refuses an occupied app path" "got: $OUT"
[[ -f "$APPS/Occupied.app/Contents/marker" ]] && pass "the app that was there is untouched" \
    || fail "the app that was there is untouched" "it was replaced"

print -r -- ""
print -r -- "vendor verification rejects a signature that only looks like the vendor's"
# The old check searched `codesign -dv` output for TeamIdentifier=<team>. The
# signing identifier is echoed into that same output, so an ad-hoc signature
# whose identifier contained the expected line satisfied it, and an ad-hoc
# signature passes --verify too. No key needed. Both halves are asserted here:
# the fixture has to keep demonstrating the old bug, or this proves nothing.
SPOOF="$SCRATCH/Spoof.app"
/bin/mkdir -p "$SPOOF/Contents"
/usr/bin/plutil -create xml1 "$SPOOF/Contents/Info.plist"
/usr/bin/plutil -insert CFBundleIdentifier -string "com.openai.codex" "$SPOOF/Contents/Info.plist"
/usr/bin/plutil -insert CFBundleVersion -string "1" "$SPOOF/Contents/Info.plist"
/usr/bin/codesign --force --sign - -i $'com.openai.codex\nTeamIdentifier=2DC432GLL2' \
    "$SPOOF" >/dev/null 2>&1
[[ "$(/usr/bin/codesign -dv --verbose=4 "$SPOOF" 2>&1)" == *"TeamIdentifier=2DC432GLL2"* ]] \
    && pass "the fixture still satisfies the old substring search" \
    || fail "the fixture still satisfies the old substring search" "it no longer demonstrates the old bug"
/usr/bin/codesign --verify --deep --strict "$SPOOF" >/dev/null 2>&1 \
    && pass "and still passes a plain strict verify" \
    || fail "and still passes a plain strict verify" "the ad-hoc seal no longer verifies"
if /usr/bin/codesign --verify --deep --strict \
    -R '=anchor apple generic and identifier "com.openai.codex" and certificate leaf[subject.OU] = "2DC432GLL2"' \
    "$SPOOF" >/dev/null 2>&1; then
    fail "the Apple-anchored requirement rejects it" "the spoofed bundle satisfied the requirement"
else
    pass "the Apple-anchored requirement rejects it"
fi
# Asserting codesign's behaviour is not enough: the point is that Doppel's own
# vendor check applies it. Drive the real CLI with the spoof as its primary. The
# appcast is pointed at a closed port so that if the check ever stops rejecting
# the spoof, this reports the feed error instead and the assertion fails rather
# than reaching for the network.
GUARD_OUT="$(DOPPEL_HOME="$SCRATCH/spoof-home" DOPPEL_PRIMARY_APP="$SPOOF" \
    DOPPEL_APPCAST_URL="http://127.0.0.1:9/unused.xml" \
    "$CLI" update check 2>&1)"
[[ "$GUARD_OUT" == *"not valid vendor-signed code"* ]] \
    && pass "and Doppel's own vendor check refuses the spoofed primary" \
    || fail "and Doppel's own vendor check refuses the spoofed primary" "got: $GUARD_OUT"
# The engine keeps its own copy of the requirement, so the CLI passing proves
# nothing about it: editing only the engine's copy would otherwise pass the
# suite. Give it the minimum assets its preflight demands, then point it at the
# spoof.
ENGINE_DIR="$SCRATCH/engine-probe"
/bin/mkdir -p "$ENGINE_DIR/bin" "$ENGINE_DIR/assets" "$ENGINE_DIR/engine"
write_config_file "$ENGINE_DIR" "Engine Probe" "com.example.engine-probe" \
    "codex-engine-probe" "$SCRATCH/engine-profile" "$SCRATCH/engine-codex" "3B82F6"
for asset in bin/doppel-launcher bin/doppel-alert bin/doppel-url-handler \
             bin/doppel engine/doppel-engine.zsh engine/patch-deep-link.py \
             patch-deep-link.py assets/icon.icns assets/icon.png; do
    : > "$ENGINE_DIR/$asset"
done
/bin/chmod 755 "$ENGINE_DIR/bin/doppel-launcher" "$ENGINE_DIR/bin/doppel" \
    "$ENGINE_DIR/engine/doppel-engine.zsh"
GUARD_OUT="$(DOPPEL_NO_ALERT=1 DOPPEL_ASSET_ROOT="$ENGINE_DIR" \
    DOPPEL_STATE_ROOT="$SCRATCH/engine-state" DOPPEL_PRIMARY_APP="$SPOOF" \
    /bin/zsh "$REPO_ROOT/engine/doppel-engine.zsh" install "$SCRATCH/EngineProbe.app" 2>&1)"
[[ "$GUARD_OUT" == *"not Apple-anchored OpenAI-signed code"* ]] \
    && pass "and the engine's own copy of the check refuses it too" \
    || fail "and the engine's own copy of the check refuses it too" "got: $GUARD_OUT"

print -r -- ""
print -r -- "the cached-installer fallback refuses anything it cannot verify"
# When the installed primary fails verification a rebuild may fall back to an
# exact-build official DMG that Doppel previously verified and kept. Nothing
# exercised that arm, so its guards are asserted here with the spoofed primary
# above: no 1.4GB image needed, because each guard fires before the mount.
FALLBACK_HOME="$SCRATCH/fallback-home"
FALLBACK_DIR="$FALLBACK_HOME/instances/fallback-probe"
/bin/mkdir -p "$FALLBACK_DIR"
write_config_file "$FALLBACK_DIR" "Fallback Probe" "com.example.fallback-probe" \
    "codex-fallback-probe" "$SCRATCH/fallback-profile" "$SCRATCH/fallback-codex" "3B82F6"
print -r -- "$SCRATCH/fallback-apps" > "$FALLBACK_DIR/install-root"
# The spoof reports CFBundleVersion 1, so the fallback looks for build 1.
FALLBACK_OUT="$(DOPPEL_HOME="$FALLBACK_HOME" DOPPEL_PRIMARY_APP="$SPOOF" \
    DOPPEL_UPDATE_ROOT="$SCRATCH/fallback-updates" \
    "$CLI" rebuild "Fallback Probe" 2>&1)"
[[ "$FALLBACK_OUT" == *"no verified official installer is cached for build 1"* ]] \
    && pass "an unverifiable primary with no cached installer is refused" \
    || fail "an unverifiable primary with no cached installer is refused" "got: $FALLBACK_OUT"
# A file at the expected path is not enough; it has to pass its own checksum.
/bin/mkdir -p "$SCRATCH/fallback-updates/Official/1"
print -r -- "not a disk image" > "$SCRATCH/fallback-updates/Official/1/ChatGPT.dmg"
FALLBACK_OUT="$(DOPPEL_HOME="$FALLBACK_HOME" DOPPEL_PRIMARY_APP="$SPOOF" \
    DOPPEL_UPDATE_ROOT="$SCRATCH/fallback-updates" \
    "$CLI" rebuild "Fallback Probe" 2>&1)"
[[ "$FALLBACK_OUT" == *"failed its disk-image checksum"* ]] \
    && pass "a cached installer that is not a valid image is refused" \
    || fail "a cached installer that is not a valid image is refused" "got: $FALLBACK_OUT"
[[ ! -d "$SCRATCH/fallback-apps/Fallback Probe.app" ]] \
    && pass "and neither refusal built anything" \
    || fail "and neither refusal built anything" "an app was produced"

print -r -- ""
print -r -- "a primary the vendor updated on its own leaves the instances behind"
# ChatGPT's own Sparkle updater installs into /Applications without telling
# Doppel, and it never touches the managed instances. The feed then agrees with
# the primary while every instance is still on the build it was cloned from —
# a state that used to report "up to date" and refuse `update apply` with "not
# newer than the installed build", leaving no way forward at all.
#
# The appcast is a local file so this asserts the real parsing without the
# network, and the instance is a stub bundle: only the build it records matters
# here, and building a real clone costs a minute for nothing extra.
DRIFT_HOME="$SCRATCH/drift-home"
DRIFT_APPS="$SCRATCH/drift-apps"
DRIFT_DIR="$DRIFT_HOME/instances/drift-probe"
DRIFT_INFO="$DRIFT_APPS/Drift Probe.app/Contents/Info.plist"
DRIFT_BUILD="$(/usr/bin/plutil -extract CFBundleVersion raw "$PRIMARY/Contents/Info.plist")"
DRIFT_SHORT="$(/usr/bin/plutil -extract CFBundleShortVersionString raw "$PRIMARY/Contents/Info.plist")"
/bin/mkdir -p "$DRIFT_DIR" "${DRIFT_INFO:h}"
write_config_file "$DRIFT_DIR" "Drift Probe" "com.example.drift-probe" \
    "codex-drift-probe" "$SCRATCH/drift-profile" "$SCRATCH/drift-codex" "3B82F6"
print -r -- "$DRIFT_APPS" > "$DRIFT_DIR/install-root"
cat > "$SCRATCH/appcast.xml" <<XML
<?xml version="1.0" standalone="yes"?>
<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
  <channel>
    <item>
      <sparkle:version>$DRIFT_BUILD</sparkle:version>
      <sparkle:shortVersionString>$DRIFT_SHORT</sparkle:shortVersionString>
      <enclosure url="https://persistent.oaistatic.com/codex-app-prod/ChatGPT-darwin-arm64-$DRIFT_SHORT.zip" />
    </item>
  </channel>
</rss>
XML
record_source_build() {
    /usr/bin/plutil -create xml1 "$DRIFT_INFO"
    /usr/bin/plutil -insert CFBundleIdentifier -string "com.example.drift-probe" "$DRIFT_INFO"
    /usr/bin/plutil -insert DoppelSourceBundleVersion -string "$1" "$DRIFT_INFO"
}
drift_check() {
    DOPPEL_HOME="$DRIFT_HOME" DOPPEL_APPCAST_URL="file://${SCRATCH// /%20}/appcast.xml" \
        "$CLI" update check --porcelain 2>&1
}
record_source_build "1"
DRIFT_OUT="$(drift_check)"
check "an instance behind the primary is reported as drift" \
    "$(print -r -- "$DRIFT_OUT" | /usr/bin/awk -F'\t' '{print $1}')" "stale-instances"
check "and the count says how many are behind" \
    "$(print -r -- "$DRIFT_OUT" | /usr/bin/awk -F'\t' '{print $7}')" "1"
check "while the columns still describe what is installed" \
    "$(print -r -- "$DRIFT_OUT" | /usr/bin/awk -F'\t' '{print $2}')" "$DRIFT_BUILD"
record_source_build "$DRIFT_BUILD"
DRIFT_OUT="$(drift_check)"
check "an instance built from the installed primary is current" \
    "$(print -r -- "$DRIFT_OUT" | /usr/bin/awk -F'\t' '{print $1}')" "current"
check "and nothing is counted as behind" \
    "$(print -r -- "$DRIFT_OUT" | /usr/bin/awk -F'\t' '{print $7}')" "0"
# The other direction is not drift Doppel can offer to fix: rebuilding an
# instance onto an older primary is a downgrade, and calling it "behind" would
# ask for consent on a false statement.
record_source_build "$(( DRIFT_BUILD + 1 ))"
DRIFT_OUT="$(drift_check)"
check "an instance ahead of the primary is not reported as behind" \
    "$(print -r -- "$DRIFT_OUT" | /usr/bin/awk -F'\t' '{print $1}')" "current"
check "and is not counted as behind" \
    "$(print -r -- "$DRIFT_OUT" | /usr/bin/awk -F'\t' '{print $7}')" "0"
check "but is still counted, in its own column" \
    "$(print -r -- "$DRIFT_OUT" | /usr/bin/awk -F'\t' '{print $8}')" "1"
DRIFT_HUMAN="$(DOPPEL_HOME="$DRIFT_HOME" DOPPEL_APPCAST_URL="file://${SCRATCH// /%20}/appcast.xml" \
    "$CLI" update check 2>&1)"
[[ "$DRIFT_HUMAN" == *"newer build than the installed app"* && "$DRIFT_HUMAN" != *"older version"* ]] \
    && pass "and is described in the direction it is actually in" \
    || fail "and is described in the direction it is actually in" "got: $DRIFT_HUMAN"
record_source_build "$DRIFT_BUILD"
# Applying the build the primary already carries has to get past the version
# comparison and the prepared-download requirement and reach the instances. That
# it then rebuilds the right ones is what qa/update-reconcile.zsh proves against
# real clones; reaching an empty inventory is all this cheap home can show.
DRIFT_OUT="$(DOPPEL_HOME="$SCRATCH/reconcile-empty" \
    DOPPEL_APPCAST_URL="file://${SCRATCH// /%20}/appcast.xml" \
    "$CLI" update apply "$DRIFT_BUILD" 2>&1)"
[[ "$DRIFT_OUT" == *"no installed managed instances"* ]] \
    && pass "the installed build reaches the instances instead of being refused" \
    || fail "the installed build reaches the instances instead of being refused" "got: $DRIFT_OUT"
# Only equality is reconcilable: an older genuine build must still be refused,
# or a replay could walk the primary backwards.
DRIFT_OUT="$(DOPPEL_HOME="$SCRATCH/reconcile-empty" \
    DOPPEL_APPCAST_URL="file://${SCRATCH// /%20}/appcast.xml" \
    "$CLI" update apply 1 2>&1)"
[[ "$DRIFT_OUT" == *"is older than the installed build"* ]] \
    && pass "an older build is still refused" \
    || fail "an older build is still refused" "got: $DRIFT_OUT"

print -r -- ""
print -r -- "an installed copy ignores the environment overrides it must not honour"
# This guard sat below the assignments it was meant to protect once already,
# which made it a no-op that every existing check still passed. --scheme is
# compared against the primary scheme before anything touches disk, so a leaked
# DOPPEL_PRIMARY_SCHEME is observable without a network call or a clone.
GUARD_FIXTURE="$SCRATCH/Doppel.app/Contents/Resources/doppel/bin"
/bin/mkdir -p "$GUARD_FIXTURE" "${GUARD_FIXTURE:h}/engine"
/bin/cp "$CLI" "$GUARD_FIXTURE/doppel"
/bin/cp "$REPO_ROOT/engine/doppel-engine.zsh" "$REPO_ROOT/engine/patch-deep-link.py" \
    "${GUARD_FIXTURE:h}/engine/"
/bin/chmod 755 "$GUARD_FIXTURE/doppel"
# First prove the probe can detect a leak at all: from a checkout path the
# override is honoured by design, so the collision message must appear.
GUARD_OUT="$(DOPPEL_HOME="$SCRATCH/guard-checkout" DOPPEL_PRIMARY_SCHEME="codex-spoof" \
    "$CLI" create --name "Guard Probe" --tint 3B82F6 --scheme codex-spoof \
    --install-to "$APPS" 2>&1)"
[[ "$GUARD_OUT" == *"belongs to the primary app"* ]] \
    && pass "the probe detects a honoured override from a checkout" \
    || fail "the probe detects a honoured override from a checkout" "got: $GUARD_OUT"
# Then the real assertion: from an installed bundle path it must be dropped.
GUARD_USER_HOME="$SCRATCH/guard-user"
/bin/mkdir -p "$GUARD_USER_HOME"
GUARD_OUT="$(HOME="$GUARD_USER_HOME" DOPPEL_HOME="$SCRATCH/guard-bundle" DOPPEL_PRIMARY_SCHEME="codex-spoof" \
    "$GUARD_FIXTURE/doppel" create --name "Guard Probe" --tint 3B82F6 --scheme codex-spoof \
    --install-to "$APPS" 2>&1)"
[[ "$GUARD_OUT" != *"belongs to the primary app"* ]] \
    && pass "an installed copy ignores DOPPEL_PRIMARY_SCHEME" \
    || fail "an installed copy ignores DOPPEL_PRIMARY_SCHEME" "the override leaked through: $GUARD_OUT"
[[ ! -d "$APPS/Guard Probe.app" ]] && pass "and the probe installed nothing" \
    || fail "and the probe installed nothing" "$APPS/Guard Probe.app was created"
# The signing variables matter more than the scheme, and the CLI is the only
# thing that scrubs them: the engine copy that rebuild and update apply execute
# lives under instances/<slug>/, which its own guard does not match. A leak
# there lets a caller choose the certificate that signs a rebuild and have it
# recorded as that instance's pin. Observed through a stub engine, because the
# CLI never reads these itself and only passes them on.
SIGN_USER_HOME="$SCRATCH/sign-user"
SIGN_HOME="$SIGN_USER_HOME/Library/Application Support/Doppel"
SIGN_DIR="$SIGN_HOME/instances/sign-probe"
/bin/mkdir -p "$SIGN_DIR"
write_config_file "$SIGN_DIR" "Sign Probe" "com.example.sign-probe" \
    "codex-sign-probe" "$SCRATCH/sign-profile" "$SCRATCH/sign-codex" "3B82F6"
print -r -- "$SCRATCH/sign-apps" > "$SIGN_DIR/install-root"
# Exits non-zero so cmd_edit reports the stub's output instead of swallowing it.
{
    print -r -- "#!/bin/zsh"
    print -r -- 'print -r -- "leaked-sha1:${DOPPEL_SIGN_LEAF_SHA1:-none}"'
    print -r -- "exit 1"
} > "${GUARD_FIXTURE:h}/engine/doppel-engine.zsh"
/bin/chmod 755 "${GUARD_FIXTURE:h}/engine/doppel-engine.zsh"
GUARD_OUT="$(HOME="$SIGN_USER_HOME" DOPPEL_HOME="$SCRATCH/ignored-sign-home" \
    DOPPEL_SIGN_LEAF_SHA1="DEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEF" \
    "$GUARD_FIXTURE/doppel" edit "Sign Probe" --rename "Sign Probe Renamed" 2>&1)"
[[ "$GUARD_OUT" == *"leaked-sha1:none"* ]] \
    && pass "an installed copy scrubs DOPPEL_SIGN_LEAF_SHA1 before the engine runs" \
    || fail "an installed copy scrubs DOPPEL_SIGN_LEAF_SHA1 before the engine runs" "got: $GUARD_OUT"

print -r -- ""
print -r -- "building the one instance the rest of the checks share"
if ! "$CLI" create --name "$NAME" --tint A855F7 --install-to "$APPS" >/dev/null 2>&1; then
    print -u2 -r -- "  ✗ create failed; aborting"
    exit 1
fi
DIR="$DOPPEL_DIR/instances/$SLUG"
[[ -d "$(app_path)" ]] && pass "instance installed" || fail "instance installed" "missing $(app_path)"

print -r -- ""
print -r -- "the pin the launcher checks cannot be stripped from inside the bundle"
APP="$(app_path)"
PIN="$(pin_file "$APP")"
if [[ -s "$PIN" ]]; then
    pass "a requirement is recorded outside the bundle"
    REQUIREMENT="$(<"$PIN")"
    [[ "$REQUIREMENT" == *"certificate leaf"* ]] && pass "and it pins the certificate leaf" \
        || fail "and it pins the certificate leaf" "got: $REQUIREMENT"
    /usr/bin/plutil -remove DoppelPinnedRequirement "$APP/Contents/Info.plist" >/dev/null 2>&1
    print -r -- "# tampered" >> "$APP/Contents/Resources/Doppel/doppel-engine.zsh"
    /usr/bin/xattr -cr "$APP"
    /usr/bin/codesign -f -s - --options runtime -i "com.openai.codex.doppel-$SLUG" "$APP" >/dev/null 2>&1
    if /usr/bin/codesign --verify --strict -R "=$REQUIREMENT" "$APP" >/dev/null 2>&1; then
        fail "stripping the key and resealing ad hoc is rejected" "it satisfied the recorded requirement"
    else
        pass "stripping the key and resealing ad hoc is rejected"
    fi
    "$CLI" rebuild "$NAME" >/dev/null 2>&1
    /usr/bin/codesign --verify --deep --strict "$APP" >/dev/null 2>&1 \
        && pass "and a rebuild puts it right" || fail "and a rebuild puts it right" "still invalid"
else
    fail "a requirement is recorded outside the bundle" "nothing at $PIN (is a signing identity set up?)"
fi

print -r -- ""
print -r -- "a rebuild that has nothing to do says so"
run_real rebuild "$NAME"
[[ "$OUT" == *"already up to date"* ]] && pass "no-op reported as a no-op" \
    || fail "no-op reported as a no-op" "got: $OUT"

# tccd's hardened-runtime prompting policy denies microphone and camera to a
# process without the matching device entitlements — silently: no prompt, no
# System Settings row. The launcher is the process that runs the menu's native
# requests, so its signature has to carry the vendor's device entitlements.
print -r -- ""
print -r -- "the launcher can pass tccd's hardened-runtime prompting policy"
LAUNCHER_ENTITLEMENTS="$(/usr/bin/codesign -d --entitlements - --xml "$APP/Contents/MacOS/ChatGPT" 2>/dev/null)"
[[ "$LAUNCHER_ENTITLEMENTS" == *com.apple.security.device.audio-input* ]] \
    && pass "the launcher carries the microphone entitlement" \
    || fail "the launcher carries the microphone entitlement" "tccd would deny the prompt silently"
[[ "$LAUNCHER_ENTITLEMENTS" == *com.apple.security.device.camera* ]] \
    && pass "the launcher carries the camera entitlement" \
    || fail "the launcher carries the camera entitlement" "tccd would deny the prompt silently"

print -r -- ""
print -r -- "an instance built before the entitlement fix is reported as needing a rebuild"
INFO="$APP/Contents/Info.plist"
/bin/cp "$INFO" "$SCRATCH/Info.plist.saved"
/usr/bin/plutil -replace DoppelEngineVersion -string "21" "$INFO"
run_real permissions check --porcelain "$NAME"
[[ "$OUT" == *$'permission-check\toutdated'* ]] \
    && pass "permissions check flags the stale engine instead of probing it" \
    || fail "permissions check flags the stale engine instead of probing it" "got: $OUT"
run_real permissions request "$NAME" microphone
[[ $STATUS -ne 0 && "$OUT" == *"must be rebuilt"* ]] \
    && pass "a microphone request on a stale engine fails with the rebuild hint" \
    || fail "a microphone request on a stale engine fails with the rebuild hint" "got ($STATUS): $OUT"
run_real permissions request "$NAME"
[[ $STATUS -ne 0 && "$OUT" == *"must be rebuilt"* ]] \
    && pass "a bulk request on a stale engine fails instead of skipping devices silently" \
    || fail "a bulk request on a stale engine fails instead of skipping devices silently" "got ($STATUS): $OUT"
/bin/cp "$SCRATCH/Info.plist.saved" "$INFO"
run_real permissions check --porcelain "$NAME"
[[ "$OUT" == *$'microphone\t'* && "$OUT" != *$'permission-check\toutdated'* ]] \
    && pass "an in-step instance reports live permission statuses" \
    || fail "an in-step instance reports live permission statuses" "got: $OUT"

print -r -- ""
print -r -- "rollback copies do not pile up"
BACKUPS="$DOPPEL_DIR/state/com.openai.codex.doppel-$SLUG/Backups"
/bin/mkdir -p "$BACKUPS/older.app.rollback" "$BACKUPS/oldest.app.rollback"
# Named, so the check never reaches past its own throwaway instance.
"$CLI" prune "$NAME" >/dev/null 2>&1
check "prune keeps one rollback" \
    "$(/bin/ls -d "$BACKUPS"/*.rollback(N/) 2>/dev/null | /usr/bin/wc -l | /usr/bin/tr -d ' ')" "1"

print -r -- ""
print -r -- "stored rollback apps do not appear as duplicate installed apps"
DISCOVERABLE="$SCRATCH/native-tools/state/com.example.native/Backups/Old.app.rollback"
VENDOR_BACKUP="$SCRATCH/native-tools/updates/Backups/ChatGPT.app"
/bin/mkdir -p "$DISCOVERABLE/Contents"
/usr/bin/plutil -create xml1 "$DISCOVERABLE/Contents/Info.plist"
/usr/bin/plutil -insert CFBundleIdentifier -string com.example.native \
    "$DISCOVERABLE/Contents/Info.plist"
/bin/mkdir -p "$VENDOR_BACKUP/Contents"
/usr/bin/plutil -create xml1 "$VENDOR_BACKUP/Contents/Info.plist"
/usr/bin/plutil -insert CFBundleIdentifier -string com.openai.codex \
    "$VENDOR_BACKUP/Contents/Info.plist"
run_isolated native-tools native-tools repair
[[ -f "$DISCOVERABLE/Contents/Info.plist.doppel-rollback" ]] \
    && pass "repair hides the signed plist from app discovery" \
    || fail "repair hides the signed plist from app discovery" "the plist stayed in bundle position"
[[ ! -e "$DISCOVERABLE/Contents/Info.plist" ]] \
    && pass "the stored directory is no longer an application bundle" \
    || fail "the stored directory is no longer an application bundle" "Info.plist is still discoverable"
[[ -f "$SCRATCH/native-tools/updates/.Backups/ChatGPT.app/Contents/Info.plist" ]] \
    && pass "the protected primary rollback moves whole into hidden storage" \
    || fail "the protected primary rollback moves whole into hidden storage" "the vendor bundle did not move intact"
run_isolated native-tools native-tools status --porcelain
[[ "$OUT" == *$'rollbacks\t0'* ]] \
    && pass "native-tool status confirms app discovery is clean" \
    || fail "native-tool status confirms app discovery is clean" "got: $OUT"
/bin/mv "$DISCOVERABLE/Contents/Info.plist.doppel-rollback" \
    "$DISCOVERABLE/Contents/Info.plist"
check "the original identifier is byte-for-byte restorable" \
    "$(/usr/bin/plutil -extract CFBundleIdentifier raw "$DISCOVERABLE/Contents/Info.plist")" \
    "com.example.native"

print -r -- ""
print -r -- "data the instance does not own is never purged"
ORIGINAL_PROFILE="$(config_field "$DIR" DOPPEL_PROFILE_ROOT)"
for guarded in "$HOME" "$HOME/Documents" "$HOME/.codex" "$HOME/Library/Application Support/Codex"; do
    set_profile_root "$DIR" "$guarded"
    # This assertion targets the purge guard itself. The real Veridue profile
    # deliberately is Application Support/Codex and may be open while QA runs;
    # suppress process discovery in this existing dry-run mode so an earlier
    # live-profile refusal cannot mask whether the protected path is rejected.
    OUT="$(DOPPEL_DEV=1 DOPPEL_IAB_DRY_RUN=1 "$CLI" remove "$NAME" --purge-data 2>&1)"
    STATUS=$?
    [[ "$OUT" == *"refusing to purge"* ]] && pass "refuses to purge $guarded" \
        || fail "refuses to purge $guarded" "got: $OUT"
    [[ -d "$(app_path)" ]] || fail "  and removes nothing when it refuses" "$guarded: the app went anyway"
done
set_profile_root "$DIR" "$ORIGINAL_PROFILE"
check "the instance's own profile is purgeable again" \
    "$(protected_check=$(config_field "$DIR" DOPPEL_PROFILE_ROOT); print -r -- "${protected_check:t}")" "$NAME"

print -r -- ""
print -r -- "names that would become indistinguishable are refused"
/bin/mkdir -p "$DOPPEL_DIR/instances/$SIBLING_SLUG"
write_config_file "$DOPPEL_DIR/instances/$SIBLING_SLUG" "$SIBLING_NAME" \
    "com.openai.codex.doppel-$SIBLING_SLUG" "codex-$SIBLING_SLUG" \
    "$SCRATCH/sibling-profile" "$SCRATCH/sibling-codex" "EF4444"
run_real edit "$NAME" --rename "${SIBLING_NAME// /-}"
[[ "$OUT" == *"too close to"* ]] && pass "a rename that collides on the identifier is refused" \
    || fail "a rename that collides on the identifier is refused" "got: $OUT"
check "the instance kept its name" "$(config_field "$DIR" DOPPEL_DISPLAY_NAME)" "$NAME"
check "and the sibling is still reachable by its own name" \
    "$("$CLI" list --porcelain | /usr/bin/awk -F'\t' -v n="$SIBLING_NAME" '$2 == n {print $1}')" \
    "$SIBLING_SLUG"

print -r -- ""
print -r -- "a rename that cannot finish changes nothing at all"
/bin/mkdir -p "$APPS/Taken.app"
run_real edit "$NAME" --rename "Taken"
[[ "$OUT" == *"an app already exists"* ]] && pass "refused" || fail "refused" "got: $OUT"
check "the config was not renamed anyway" "$(config_field "$DIR" DOPPEL_DISPLAY_NAME)" "$NAME"
[[ -d "$(app_path)" ]] && pass "the bundle is still where the config says" \
    || fail "the bundle is still where the config says" "$(app_path) is gone"

print -r -- ""
print -r -- "a rename that does finish takes its pin with it"
OLD_APP="$(app_path)"
run_real edit "$NAME" --rename "$NAME Renamed"
NEW_APP="$(app_path)"
[[ "$NEW_APP" != "$OLD_APP" ]] && pass "the bundle moved" || fail "the bundle moved" "still at $OLD_APP"
[[ -s "$(pin_file "$NEW_APP")" ]] && pass "a pin is recorded for the new path" \
    || fail "a pin is recorded for the new path" "nothing at $(pin_file "$NEW_APP")"
[[ ! -e "$(pin_file "$OLD_APP")" ]] && pass "and the old one is not left behind" \
    || fail "and the old one is not left behind" "$(pin_file "$OLD_APP") survived"

print -r -- ""
print -r -- "an edit does not open an instance that was not running"
APP="$(app_path)"
/usr/bin/pgrep -f "${APP}/Contents/MacOS/" >/dev/null 2>&1 && \
    /usr/bin/osascript -e "tell application id \"com.openai.codex.doppel-$SLUG\" to quit" >/dev/null 2>&1
DOPPEL_RELAUNCH=1 "$CLI" edit "$NAME Renamed" --tint 84CC16 >/dev/null 2>&1
/bin/sleep 3
if /usr/bin/pgrep -f "${APP}/Contents/MacOS/" >/dev/null 2>&1; then
    fail "a closed instance stays closed" "the edit opened it"
    /usr/bin/osascript -e "tell application id \"com.openai.codex.doppel-$SLUG\" to quit" >/dev/null 2>&1
else
    pass "a closed instance stays closed"
fi

print -r -- ""
print -r -- "claiming the browser extension host moves only the path it is told to"
# Against a throwaway browser-support root, so a real Chrome profile is never
# written to. The instance needs an extension host on disk to be claimable,
# which is what a launched instance would have installed itself.
BROWSER_ROOT="$SCRATCH/browser-support"
CLAIM_HOME="$SCRATCH/codex-claim"
CLAIM_HOST="$CLAIM_HOME/plugins/cache/openai-bundled/chrome/latest/extension-host/macos/arm64"
/bin/mkdir -p "$CLAIM_HOST"
: > "$CLAIM_HOST/ChatGPT for Chrome"
/bin/chmod 755 "$CLAIM_HOST/ChatGPT for Chrome"

# Chrome and Edge both, because "Microsoft Edge" is the directory with a space
# in it and so the one that would catch a missing quote.
write_host_manifest() {
    /bin/mkdir -p "${1:h}"
    /bin/cat > "$1" <<JSON
{
  "allowed_origins": [ "chrome-extension://hehggadaopoacecdllhhajmbjkdcmajg/" ],
  "description": "ChatGPT browser native messaging host",
  "name": "com.openai.codexextension",
  "path": "$HOME/.codex-someone-else/plugins/cache/openai-bundled/chrome/latest/extension-host/macos/arm64/ChatGPT for Chrome",
  "type": "stdio"
}
JSON
}
CLAIM_MANIFEST="$BROWSER_ROOT/Google/Chrome/NativeMessagingHosts/com.openai.codexextension.json"
CLAIM_MANIFEST_EDGE="$BROWSER_ROOT/Microsoft Edge/NativeMessagingHosts/com.openai.codexextension.json"
write_host_manifest "$CLAIM_MANIFEST"
write_host_manifest "$CLAIM_MANIFEST_EDGE"

# Same capture contract as run_real, plus the per-run browser root this feature
# needs, so these cases assert on exit status and not just on wording.
run_claim() {
    OUT="$(DOPPEL_BROWSER_SUPPORT_ROOT="$1" "$CLI" "${@:2}" 2>&1)"
    STATUS=$?
    return 0
}
manifest_field() {
    /usr/bin/python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))[sys.argv[2]])' "$1" "$2"
}

CLAIM_DIR="$DOPPEL_DIR/instances/$SLUG"
set_codex_home() {
    write_config_file "$1" \
        "$(config_field "$1" DOPPEL_DISPLAY_NAME)" \
        "$(config_field "$1" DOPPEL_BUNDLE_ID)" \
        "$(config_field "$1" DOPPEL_URL_SCHEME)" \
        "$(config_field "$1" DOPPEL_PROFILE_ROOT)" \
        "$2" \
        "$(config_field "$1" DOPPEL_TINT)"
}
CLAIM_SAVED_HOME="$(config_field "$CLAIM_DIR" DOPPEL_CODEX_HOME)"
set_codex_home "$CLAIM_DIR" "$CLAIM_HOME"

run_claim "$BROWSER_ROOT" native-tools claim-browser "$NAME Renamed"
check "claiming succeeds" "$STATUS" "0"
[[ "$OUT" == *"claimed Chrome"* && "$OUT" == *"claimed Edge"* ]] && \
    pass "the claim reports every browser it moved" \
    || fail "the claim reports every browser it moved" "got: $OUT"
check "the path now points at this instance's own host" \
    "$(manifest_field "$CLAIM_MANIFEST" path)" "$CLAIM_HOST/ChatGPT for Chrome"
check "a browser directory with a space in it is rewritten too" \
    "$(manifest_field "$CLAIM_MANIFEST_EDGE" path)" "$CLAIM_HOST/ChatGPT for Chrome"
check "the vendor's own host name is left alone" \
    "$(manifest_field "$CLAIM_MANIFEST" name)" "com.openai.codexextension"
check "and so are the origins it allows" \
    "$(/usr/bin/python3 -c 'import json,sys; print(",".join(json.load(open(sys.argv[1]))["allowed_origins"]))' "$CLAIM_MANIFEST")" \
    "chrome-extension://hehggadaopoacecdllhhajmbjkdcmajg/"

print -r -- ""
print -r -- "status names the instance that holds the extension host"
# Asserted while the instance still owns the claim, and on the owner column
# itself: the attribution is the only part of this that has to be right.
run_claim "$BROWSER_ROOT" native-tools status --porcelain
[[ "$OUT" == *$'in-app-browser\tassigned\t'* || \
   "$OUT" == *$'in-app-browser\tunassigned'* ]] && \
    pass "the movable in-app-browser engine state is reported" \
    || fail "the movable in-app-browser engine state is reported" "got: $OUT"
check "the owner column names this instance" \
    "$(print -r -- "$OUT" | /usr/bin/awk -F'\t' '$1 == "browser-host" && $2 == "Chrome" {print $3}')" \
    "$NAME Renamed"

print -r -- ""
print -r -- "one browser can be assigned without disturbing the others"
# This is what lets two instances browse at the same time, one per browser.
write_host_manifest "$CLAIM_MANIFEST"
write_host_manifest "$CLAIM_MANIFEST_EDGE"
run_claim "$BROWSER_ROOT" native-tools claim-browser --browser Chrome "$NAME Renamed"
check "a single-browser claim succeeds" "$STATUS" "0"
[[ "$OUT" == *"claimed Chrome"* && "$OUT" != *"claimed Edge"* ]] && \
    pass "only the named browser is reported" \
    || fail "only the named browser is reported" "got: $OUT"
check "the named browser moved" \
    "$(manifest_field "$CLAIM_MANIFEST" path)" "$CLAIM_HOST/ChatGPT for Chrome"
check "and the other one was left where it was" \
    "$(manifest_field "$CLAIM_MANIFEST_EDGE" path)" \
    "$HOME/.codex-someone-else/plugins/cache/openai-bundled/chrome/latest/extension-host/macos/arm64/ChatGPT for Chrome"

run_claim "$BROWSER_ROOT" native-tools claim-browser --browser Safari "$NAME Renamed"
check "a browser Doppel does not know is refused" "$STATUS" "1"
[[ "$OUT" == *"unknown browser: Safari"* && "$OUT" == *"Brave, Chrome, Chromium, Edge"* ]] && \
    pass "and the refusal lists the ones it does know, in order" \
    || fail "and the refusal lists the ones it does know, in order" "got: $OUT"

print -r -- ""
print -r -- "claiming is idempotent and never invents a registration"
# From a state where every registration already belongs to this instance, so a
# second claim has to report nothing moved at all.
run_claim "$BROWSER_ROOT" native-tools claim-browser "$NAME Renamed"
run_claim "$BROWSER_ROOT" native-tools claim-browser "$NAME Renamed"
check "claiming twice still succeeds" "$STATUS" "0"
[[ "$OUT" == *"already points at"* && "$OUT" != *claimed* ]] && \
    pass "claiming twice is a no-op, not a rewrite" \
    || fail "claiming twice is a no-op, not a rewrite" "got: $OUT"

run_claim "$SCRATCH/no-browser-here" native-tools claim-browser "$NAME Renamed"
check "a missing registration is an error" "$STATUS" "1"
[[ "$OUT" == *"no ChatGPT browser-extension registration was found"* ]] && \
    pass "with no registration installed it says so instead of creating one" \
    || fail "with no registration installed it says so instead of creating one" "got: $OUT"
[[ ! -e "$SCRATCH/no-browser-here/Google/Chrome/NativeMessagingHosts/com.openai.codexextension.json" ]] && \
    pass "and it invents no manifest of its own" \
    || fail "and it invents no manifest of its own" "one was created"

print -r -- ""
print -r -- "an unreadable registration is reported, not half-applied in silence"
write_host_manifest "$CLAIM_MANIFEST"
print -r -- "not json at all" > "$CLAIM_MANIFEST_EDGE"
run_claim "$BROWSER_ROOT" native-tools claim-browser "$NAME Renamed"
check "the command fails" "$STATUS" "1"
[[ "$OUT" == *"could not be rewritten and were left alone: Edge"* ]] && \
    pass "it names the registration it could not rewrite" \
    || fail "it names the registration it could not rewrite" "got: $OUT"
[[ "$OUT" != *Traceback* ]] && pass "and does not leak a Python traceback" \
    || fail "and does not leak a Python traceback" "got: $OUT"
check "the readable one still moved" \
    "$(manifest_field "$CLAIM_MANIFEST" path)" "$CLAIM_HOST/ChatGPT for Chrome"

set_codex_home "$CLAIM_DIR" "$CLAIM_SAVED_HOME"

print -r -- ""
print -r -- "an installed instance whose registry directory is gone is still adoptable"
# The registry is a record of an instance, not the only copy of one: the bundle
# carries the config and icon its own engine reads at launch. Losing the
# directory used to make every inventory-driven command report an empty Mac,
# including the update the menu app had just offered.
# :a because that is what the CLI records: adopt normalises the path it is
# given so install-root is something app_path_for can rebuild from, and TMPDIR
# on macOS ends in a slash.
readonly ADOPT_HOME="${SCRATCH:a}/adopt-user"
readonly ADOPT_STATE="$SCRATCH/adopt-state"
readonly ADOPT_APPS="$ADOPT_HOME/Applications"
readonly ADOPT_APP="$ADOPT_APPS/Doppel Adopt.app"
readonly ADOPT_PAYLOAD="$ADOPT_APP/Contents/Resources/Doppel"
fabricate_adoptable_bundle() {
    local name="${1:-Doppel Adopt}" id="${2:-com.example.doppel-adopt}" scheme="${3:-codex-adopt}"
    local app="$ADOPT_APPS/$name.app" payload
    payload="$app/Contents/Resources/Doppel"
    /bin/mkdir -p "$payload/assets" "$app/Contents/MacOS"
    write_config_file "$payload" "$name" "$id" "$scheme" \
        "$ADOPT_HOME/Library/Application Support/$name" "$ADOPT_HOME/.codex-adopt" "3B82F6"
    print -r -- "icns" > "$payload/assets/icon.icns"
    print -r -- "png" > "$payload/assets/icon.png"
}
# HOME confines the first scan root; /Applications is the second, and a Mac that
# keeps a managed clone there would otherwise let a real instance into a scratch
# run. The override exists for exactly this and is stripped from an installed
# copy along with the rest.
run_adopt() {
    OUT="$(HOME="$ADOPT_HOME" DOPPEL_HOME="$ADOPT_STATE" \
        DOPPEL_ADOPT_SCAN_ROOTS="$ADOPT_APPS" "$CLI" "$@" 2>&1)"
    STATUS=$?
    return 0
}
/bin/mkdir -p "$ADOPT_APPS"
fabricate_adoptable_bundle

run_adopt list
[[ "$OUT" == *"no instances"* && "$OUT" == *"not registered with Doppel"* && "$OUT" == *"$ADOPT_APP"* ]] \
    && pass "an empty registry names the managed app it cannot see" \
    || fail "an empty registry names the managed app it cannot see" "got: $OUT"

# A payload is data. Reading these configs by sourcing them was safe only while
# every one of them lived in a directory Doppel had written; the scan reads them
# out of app bundles, which anything running as the user can write. A planted
# bundle's config used to run during `list` — and during the update check the
# menu app makes unattended every six hours — before a single field had been
# looked at, which is to say before any of the validation below.
readonly ADOPT_CANARY="$SCRATCH/adopt-canary"
# Both shapes: a command on its own line, and a substitution standing where a
# value belongs. The value comes first, because the parser stops at the first
# line naming the field it was asked for.
{
    printf 'DOPPEL_DISPLAY_NAME=$(/usr/bin/touch %q)\n' "$ADOPT_CANARY"
    print -r -- "DOPPEL_BUNDLE_ID=com.example.doppel-hostile"
    print -r -- "DOPPEL_URL_SCHEME=codex-hostile"
    printf 'DOPPEL_PROFILE_ROOT=%q\n' "$ADOPT_HOME/Library/hostile"
    printf 'DOPPEL_CODEX_HOME=%q\n' "$ADOPT_HOME/.codex-hostile"
    print -r -- "DOPPEL_TINT=3B82F6"
    printf '/usr/bin/touch %q\n' "$ADOPT_CANARY"
} > "$ADOPT_PAYLOAD/instance-config.zsh"
run_adopt list
[[ ! -e "$ADOPT_CANARY" ]] \
    && pass "a hostile payload is read, not run, by the scan" \
    || fail "a hostile payload is read, not run, by the scan" "the payload executed during list"
OUT="$(HOME="$ADOPT_HOME" DOPPEL_HOME="$ADOPT_STATE" \
    DOPPEL_ADOPT_SCAN_ROOTS="$ADOPT_APPS" \
    DOPPEL_APPCAST_URL="file://${SCRATCH// /%20}/appcast.xml" \
    "$CLI" update check 2>&1)"
[[ ! -e "$ADOPT_CANARY" ]] \
    && pass "nor by the update check the menu app runs unattended" \
    || fail "nor by the update check the menu app runs unattended" "the payload executed during update check"
run_adopt adopt --all
[[ ! -e "$ADOPT_CANARY" ]] \
    && pass "nor by adoption itself" \
    || fail "nor by adoption itself" "the payload executed during adopt"
check "and the substitution is refused as the text it is" "$STATUS" "1"
fabricate_adoptable_bundle

run_adopt list --porcelain
check "and --porcelain stays a table of instances only" "$OUT" ""

check_orphan_column() {
    print -r -- "$(HOME="$ADOPT_HOME" DOPPEL_HOME="$ADOPT_STATE" \
        DOPPEL_ADOPT_SCAN_ROOTS="$ADOPT_APPS" \
        DOPPEL_APPCAST_URL="file://${SCRATCH// /%20}/appcast.xml" \
        "$CLI" update check --porcelain 2>&1 | /usr/bin/awk -F'\t' '{print $9}')"
}
check "the unregistered count reaches the ninth porcelain column" \
    "$(check_orphan_column)" "1"

run_adopt adopt --all
check "adoption succeeds" "$STATUS" "0"
[[ "$OUT" == *"adopted: Doppel Adopt"* ]] && pass "and says what it adopted" \
    || fail "and says what it adopted" "got: $OUT"
check "the instance is registered under the slug of its current name" \
    "$(config_field "$ADOPT_STATE/instances/doppel-adopt" DOPPEL_BUNDLE_ID)" \
    "com.example.doppel-adopt"
check "the recorded install root is where the bundle actually is" \
    "$(cat "$ADOPT_STATE/instances/doppel-adopt/install-root" 2>/dev/null)" "$ADOPT_APPS"
run_adopt list --porcelain
check "and the instance resolves back to its installed app" \
    "$(print -r -- "$OUT" | /usr/bin/awk -F'\t' '{print $3 FS $4}')" \
    "$ADOPT_APP"$'\t'"installed"
# Copied out of the bundle rather than regenerated: --icon and --original-icon
# leave no tint to regenerate from, and a tinted icon would be re-derived from
# whatever artwork the primary carries today.
check "the icon comes from the bundle" \
    "$(cat "$ADOPT_STATE/instances/doppel-adopt/assets/icon.icns" 2>/dev/null)" "icns"

run_adopt adopt --all
[[ "$OUT" == *"no unregistered managed apps found"* ]] \
    && pass "a second sweep finds nothing left to adopt" \
    || fail "a second sweep finds nothing left to adopt" "got: $OUT"

run_adopt list
[[ "$OUT" != *"not registered with Doppel"* ]] \
    && pass "and the warning is gone once the app is managed" \
    || fail "and the warning is gone once the app is managed" "got: $OUT"
check "and the ninth porcelain column goes back to zero" \
    "$(check_orphan_column)" "0"
run_adopt list --porcelain
check "while --porcelain still describes only the instance, in six columns" \
    "$(print -r -- "$OUT" | /usr/bin/awk -F'\t' '{print NF}')" "6"

# A copy of a managed bundle is not a second instance: both would claim one
# bundle id, which is what Launch Services and the launcher's own slug lookup
# resolve by. The same check keeps a bundle that was moved from being adopted
# alongside the entry that already describes it.
fabricate_adoptable_bundle "Doppel Adopt Copy" "com.example.doppel-adopt" "codex-adopt-copy"
run_adopt adopt "$ADOPT_APPS/Doppel Adopt Copy.app"
check "adopting a bundle whose identity is already registered fails" "$STATUS" "1"
[[ "$OUT" == *"bundle id 'com.example.doppel-adopt' is already used by instance"* ]] \
    && pass "and it names the instance that already claims it" \
    || fail "and it names the instance that already claims it" "got: $OUT"
[[ ! -d "$ADOPT_STATE/instances/doppel-adopt-copy" ]] \
    && pass "and no second entry was left behind" \
    || fail "and no second entry was left behind" "a directory was created"
/bin/rm -rf "$ADOPT_APPS/Doppel Adopt Copy.app"

print -r -- ""
print -r -- "a payload that reads differently than it runs is refused"
# The CLI parses these configs; the engine inside each bundle still sources its
# own. Any line the parser skips is a line the engine would still run, so a
# payload could show adopt a harmless URL scheme and hand the launcher the
# primary's. Taking the last assignment would close the first of these and not
# the second, which is why the shape itself is what gets refused.
divergent_payload() {
    {
        print -r -- "DOPPEL_DISPLAY_NAME=Doppel\\ Adopt"
        print -r -- "DOPPEL_BUNDLE_ID=com.example.doppel-adopt"
        print -r -- "DOPPEL_URL_SCHEME=codex-adopt"
        printf 'DOPPEL_PROFILE_ROOT=%q\n' "$ADOPT_HOME/Library/Doppel Adopt"
        printf 'DOPPEL_CODEX_HOME=%q\n' "$ADOPT_HOME/.codex-adopt"
        print -r -- "DOPPEL_TINT=3B82F6"
        print -r -- "$1"
    } > "$ADOPT_PAYLOAD/instance-config.zsh"
    /bin/rm -rf "$ADOPT_STATE/instances"
    run_adopt adopt "$ADOPT_APP"
}
divergent_payload 'DOPPEL_URL_SCHEME=codex'
check "a field declared twice is refused" "$STATUS" "1"
[[ "$OUT" == *"not a plain list of settings"* ]] \
    && pass "and the refusal is about the shape, not the value" \
    || fail "and the refusal is about the shape, not the value" "got: $OUT"
divergent_payload 'if true; then DOPPEL_URL_SCHEME=codex; fi'
check "an assignment the parser would skip is refused too" "$STATUS" "1"
divergent_payload 'DOPPEL_URL_SCHEME=codex-adopt'
check "and a duplicate that agrees with itself is still refused" "$STATUS" "1"
fabricate_adoptable_bundle
run_adopt adopt "$ADOPT_APP"
check "while the shape write_config produces is adopted" "$STATUS" "0"
/bin/rm -rf "$ADOPT_STATE/instances"

run_adopt adopt ""
check "an empty app path is a usage error, not a silent success" "$STATUS" "1"

print -r -- ""
print -r -- "adoption re-validates a payload it did not just write"
# The payload sits in a user-writable bundle. Trusting it because Doppel wrote
# it once would trust whatever edited it since.
adopt_reject() {
    local label="$1" name="$2" expect="$3"
    /bin/rm -rf "$ADOPT_STATE/instances"
    run_adopt adopt "$ADOPT_APPS/$name.app"
    if (( STATUS != 0 )) && [[ "$OUT" == *"$expect"* ]]; then
        pass "$label"
    else
        fail "$label" "status $STATUS, got: $OUT"
    fi
    [[ ! -d "$ADOPT_STATE/instances/$(print -r -- "$name" | /usr/bin/tr '[:upper:]' '[:lower:]' | /usr/bin/sed -E 's/[^a-z0-9]+/-/g')" ]] \
        && pass "  and nothing was registered" \
        || fail "  and nothing was registered" "a directory was left behind"
}
fabricate_adoptable_bundle "Doppel Adopt Primary" "com.example.doppel-primary" "codex"
adopt_reject "a payload claiming the primary URL scheme is refused" \
    "Doppel Adopt Primary" "belongs to the primary app"

fabricate_adoptable_bundle "Doppel Adopt Bad Id" "not a bundle id" "codex-badid"
adopt_reject "a payload with an unusable bundle id is refused" \
    "Doppel Adopt Bad Id" "bundle ids may contain only"

fabricate_adoptable_bundle "Doppel Adopt Renamed" "com.example.doppel-renamed" "codex-renamed"
/bin/mv "$ADOPT_APPS/Doppel Adopt Renamed.app" "$ADOPT_APPS/Doppel Adopt Moved.app"
adopt_reject "a bundle renamed in Finder is refused rather than registered as missing" \
    "Doppel Adopt Moved" "rename the bundle to"

/bin/rm -rf "$ADOPT_STATE/instances"
/bin/rm -rf "$ADOPT_PAYLOAD/assets"
run_adopt adopt "$ADOPT_APP"
check "a payload with no icon to copy is refused" "$STATUS" "1"
[[ "$OUT" == *"no icon assets to adopt"* ]] && pass "and it says what is missing" \
    || fail "and it says what is missing" "got: $OUT"

# A sweep exists to recover what can be recovered. The rejected bundles above
# are all still on disk, so this is the mixed Mac rather than a contrived one.
fabricate_adoptable_bundle
run_adopt adopt --all
check "a sweep over a mixed set still fails overall" "$STATUS" "1"
[[ "$OUT" == *"could not be adopted"* ]] && pass "and says how many it could not take" \
    || fail "and says how many it could not take" "got: $OUT"
check "but the readable one was adopted anyway" \
    "$(config_field "$ADOPT_STATE/instances/doppel-adopt" DOPPEL_BUNDLE_ID)" \
    "com.example.doppel-adopt"
/bin/rm -rf "$ADOPT_APPS/Doppel Adopt Primary.app" "$ADOPT_APPS/Doppel Adopt Bad Id.app" \
    "$ADOPT_APPS/Doppel Adopt Moved.app"
/bin/rm -rf "$ADOPT_STATE/instances"

# The message that would have saved the session this came from: an apply with
# nothing registered used to stop at "no managed instances" and leave the two
# installed clones unmentioned.
fabricate_adoptable_bundle
OUT="$(HOME="$ADOPT_HOME" DOPPEL_HOME="$ADOPT_STATE" \
    DOPPEL_ADOPT_SCAN_ROOTS="$ADOPT_APPS" \
    DOPPEL_APPCAST_URL="file://${SCRATCH// /%20}/appcast.xml" \
    "$CLI" update apply "$DRIFT_BUILD" 2>&1)"
[[ "$OUT" == *"no installed managed instances"* && "$OUT" == *"doppel adopt --all"* ]] \
    && pass "an apply with an empty registry points at the apps it cannot see" \
    || fail "an apply with an empty registry points at the apps it cannot see" "got: $OUT"

print -r -- ""
print -r -- "$PASSED passed, $FAILED failed"
(( FAILED == 0 ))
