#!/bin/zsh
# Edge-case checks: the ways Doppel used to go wrong when something about the
# request was unusual — a mistyped colour, two names that collide, a path
# already occupied, data an instance does not own.
#
# Every assertion here comes from a failure found by driving the real tool.
# Cheap cases run against a throwaway DOPPEL_HOME with nothing installed; the
# ones that need a real bundle share a single instance and clean it up.
#
#   qa/edge.zsh [--cli /path/to/doppel]

set -u
setopt PIPE_FAIL

readonly REPO_ROOT="${0:A:h:h}"
CLI="$REPO_ROOT/bin/doppel"
[[ "${1:-}" == "--cli" ]] && CLI="$2"

readonly PRIMARY="${DOPPEL_PRIMARY_APP:-/Applications/ChatGPT.app}"
readonly SCRATCH="$(/usr/bin/mktemp -d "${TMPDIR:-/tmp}/doppel-edge.XXXXXXXX")"
readonly DOPPEL_DIR="$HOME/Library/Application Support/Doppel"
readonly NAME="Doppel Edge $$"
readonly SLUG="$(print -r -- "$NAME" | /usr/bin/tr '[:upper:]' '[:lower:]' | /usr/bin/sed -E 's/[^a-z0-9]+/-/g; s/^-+|-+$//g')"
readonly SIBLING_SLUG="doppel-edge-sibling-$$"
readonly SIBLING_NAME="Doppel Edge Sibling $$"
readonly APPS="$SCRATCH/Applications"
export DOPPEL_RELAUNCH=0

typeset -i PASSED=0 FAILED=0
pass() { print -r -- "  ✓ $1"; (( PASSED += 1 )); return 0 }
fail() { print -r -- "  ✗ $1"; print -r -- "      $2"; (( FAILED += 1 )); return 0 }
check() {
    if [[ "$2" == "$3" ]]; then pass "$1"; else fail "$1" "expected '$3', got '$2'"; fi
}

typeset OUT="" STATUS=0
run_isolated() {
    local home="$SCRATCH/$1"; shift
    OUT="$(DOPPEL_HOME="$home" "$CLI" "$@" 2>&1)"
    STATUS=$?
    return 0
}
run_real() {
    OUT="$("$CLI" "$@" 2>&1)"
    STATUS=$?
    return 0
}

config_field() { ( source "$1/instance-config.zsh" 2>/dev/null || true; print -r -- "${(P)2:-}" ) }

# Rewrites a config the way the CLI writes it, so a value with spaces in it is
# escaped exactly as the real thing would escape it.
write_config_file() {
    local dir="$1" name="$2" id="$3" scheme="$4" profile="$5" codex="$6" tint="$7"
    {
        print -r -- "# Doppel instance config. Generated by doppel; do not hand-edit quoting."
        printf 'DOPPEL_DISPLAY_NAME=%q\n' "$name"
        printf 'DOPPEL_BUNDLE_ID=%q\n' "$id"
        printf 'DOPPEL_URL_SCHEME=%q\n' "$scheme"
        printf 'DOPPEL_PROFILE_ROOT=%q\n' "$profile"
        printf 'DOPPEL_CODEX_HOME=%q\n' "$codex"
        printf 'DOPPEL_TINT=%q\n' "$tint"
    } > "$dir/instance-config.zsh"
}

set_profile_root() {
    local dir="$1"
    write_config_file "$dir" \
        "$(config_field "$dir" DOPPEL_DISPLAY_NAME)" \
        "$(config_field "$dir" DOPPEL_BUNDLE_ID)" \
        "$(config_field "$dir" DOPPEL_URL_SCHEME)" \
        "$2" \
        "$(config_field "$dir" DOPPEL_CODEX_HOME)" \
        "$(config_field "$dir" DOPPEL_TINT)"
}

# Where the CLI currently thinks this instance's app lives. Re-read rather than
# remembered: a rename moves it.
app_path() { "$CLI" list --porcelain | /usr/bin/awk -F'\t' -v s="$SLUG" '$1 == s {print $3}' }
pin_file() {
    print -r -- "$DOPPEL_DIR/pins/$(print -rn -- "${1:A}" | /usr/bin/shasum -a 256 | /usr/bin/awk '{print $1}')"
}

cleanup() {
    local final
    final="$(app_path)"
    # Without --purge-data: the throwaway profile lives under $TMPDIR, and
    # purging refuses anything outside the home directory by design.
    "$CLI" remove "$(config_field "$DOPPEL_DIR/instances/$SLUG" DOPPEL_DISPLAY_NAME)" >/dev/null 2>&1 || true
    /bin/rm -rf "$DOPPEL_DIR/instances/$SLUG" 2>/dev/null || true
    /bin/rm -rf "$DOPPEL_DIR/instances/$SIBLING_SLUG" 2>/dev/null || true
    /bin/rm -rf "$DOPPEL_DIR/state/Removed/$SLUG."*(N) 2>/dev/null || true
    /bin/rm -rf "$DOPPEL_DIR/state/com.openai.codex.doppel-$SLUG" 2>/dev/null || true
    [[ -n "$final" ]] && /bin/rm -f "$(pin_file "$final")" 2>/dev/null
    /bin/rm -rf "$SCRATCH" 2>/dev/null || true
    return 0
}
trap cleanup EXIT

[[ -d "$PRIMARY" ]] || { print -u2 -r -- "the primary app is required at $PRIMARY"; exit 1 }
/bin/mkdir -p "$APPS"

print -r -- "Doppel edge cases"
print -r -- "  cli: $CLI"
print -r -- ""

print -r -- "a create that fails leaves nothing behind to trip over"
run_isolated tint create --name "Bad Hex" --tint ZZZZZZ --install-to "$APPS"
(( STATUS != 0 )) && pass "a mistyped colour is refused" || fail "a mistyped colour is refused" "exited 0"
[[ ! -d "$SCRATCH/tint/instances/bad-hex" ]] && pass "no half-built instance directory" \
    || fail "no half-built instance directory" "$SCRATCH/tint/instances/bad-hex survived"
run_isolated icon create --name "No Icon" --icon /nope/missing.icns --install-to "$APPS"
[[ "$OUT" == *"no icon file at"* ]] && pass "a missing --icon file is explained" \
    || fail "a missing --icon file is explained" "got: $OUT"
[[ ! -d "$SCRATCH/icon/instances/no-icon" ]] && pass "and leaves no directory either" \
    || fail "and leaves no directory either" "$SCRATCH/icon/instances/no-icon survived"

print -r -- ""
print -r -- "a directory without a config does not take every command down with it"
/bin/mkdir -p "$SCRATCH/broken/instances/wreckage"
run_isolated broken list --porcelain
check "list still succeeds" "$STATUS" "0"
[[ -z "$OUT" ]] && pass "and simply ignores it" || fail "and simply ignores it" "printed: $OUT"
run_isolated broken remove "Anything"
[[ "$OUT" == *"no instance named"* ]] && pass "remove says what is wrong" \
    || fail "remove says what is wrong" "got status $STATUS, output: '$OUT'"

print -r -- ""
print -r -- "a name resolves to the instance that carries it, not to the one whose"
print -r -- "directory happens to be spelled the same way"
# Two definitions whose names differ but whose identifiers would match. The
# guard above stops these being created now; a config written before it exists
# still has to resolve to the right instance rather than to its neighbour.
/bin/mkdir -p "$SCRATCH/shadow/instances/alpha" "$SCRATCH/shadow/instances/beta"
write_config_file "$SCRATCH/shadow/instances/alpha" "Alpha One" \
    "com.example.alpha" "codex-alpha" "$SCRATCH/alpha" "$SCRATCH/alpha-codex" "EF4444"
write_config_file "$SCRATCH/shadow/instances/beta" "Alpha-One" \
    "com.example.beta" "codex-beta" "$SCRATCH/beta" "$SCRATCH/beta-codex" "3B82F6"
run_isolated shadow launch "Alpha-One"
[[ "$OUT" == *"Alpha-One.app"* ]] && pass "'Alpha-One' resolves to the instance called Alpha-One" \
    || fail "'Alpha-One' resolves to the instance called Alpha-One" "got: $OUT"
run_isolated shadow launch "Alpha One"
[[ "$OUT" == *"Alpha One.app"* ]] && pass "'Alpha One' still resolves to Alpha One" \
    || fail "'Alpha One' still resolves to Alpha One" "got: $OUT"

print -r -- ""
print -r -- "an occupied path is refused rather than quietly taken over"
/bin/mkdir -p "$APPS/Occupied.app/Contents"
print -r -- "not Doppel's" > "$APPS/Occupied.app/Contents/marker"
run_isolated occupied create --name "Occupied" --tint 3B82F6 --install-to "$APPS"
[[ "$OUT" == *"an app already exists"* ]] && pass "create refuses an occupied app path" \
    || fail "create refuses an occupied app path" "got: $OUT"
[[ -f "$APPS/Occupied.app/Contents/marker" ]] && pass "the app that was there is untouched" \
    || fail "the app that was there is untouched" "it was replaced"

print -r -- ""
print -r -- "building the one instance the rest of the checks share"
if ! "$CLI" create --name "$NAME" --tint A855F7 --install-to "$APPS" >/dev/null 2>&1; then
    print -u2 -r -- "  ✗ create failed; aborting"
    exit 1
fi
DIR="$DOPPEL_DIR/instances/$SLUG"
[[ -d "$(app_path)" ]] && pass "instance installed" || fail "instance installed" "missing $(app_path)"

print -r -- ""
print -r -- "the pin the launcher checks cannot be stripped from inside the bundle"
APP="$(app_path)"
PIN="$(pin_file "$APP")"
if [[ -s "$PIN" ]]; then
    pass "a requirement is recorded outside the bundle"
    REQUIREMENT="$(<"$PIN")"
    [[ "$REQUIREMENT" == *"certificate leaf"* ]] && pass "and it pins the certificate leaf" \
        || fail "and it pins the certificate leaf" "got: $REQUIREMENT"
    /usr/bin/plutil -remove DoppelPinnedRequirement "$APP/Contents/Info.plist" >/dev/null 2>&1
    print -r -- "# tampered" >> "$APP/Contents/Resources/Doppel/doppel-engine.zsh"
    /usr/bin/xattr -cr "$APP"
    /usr/bin/codesign -f -s - --options runtime -i "com.openai.codex.doppel-$SLUG" "$APP" >/dev/null 2>&1
    if /usr/bin/codesign --verify --strict -R "=$REQUIREMENT" "$APP" >/dev/null 2>&1; then
        fail "stripping the key and resealing ad hoc is rejected" "it satisfied the recorded requirement"
    else
        pass "stripping the key and resealing ad hoc is rejected"
    fi
    "$CLI" rebuild "$NAME" >/dev/null 2>&1
    /usr/bin/codesign --verify --deep --strict "$APP" >/dev/null 2>&1 \
        && pass "and a rebuild puts it right" || fail "and a rebuild puts it right" "still invalid"
else
    fail "a requirement is recorded outside the bundle" "nothing at $PIN (is a signing identity set up?)"
fi

print -r -- ""
print -r -- "a rebuild that has nothing to do says so"
run_real rebuild "$NAME"
[[ "$OUT" == *"already up to date"* ]] && pass "no-op reported as a no-op" \
    || fail "no-op reported as a no-op" "got: $OUT"

print -r -- ""
print -r -- "rollback copies do not pile up"
BACKUPS="$DOPPEL_DIR/state/com.openai.codex.doppel-$SLUG/Backups"
/bin/mkdir -p "$BACKUPS/older.app.rollback" "$BACKUPS/oldest.app.rollback"
# Named, so the check never reaches past its own throwaway instance.
"$CLI" prune "$NAME" >/dev/null 2>&1
check "prune keeps one rollback" \
    "$(/bin/ls -d "$BACKUPS"/*.rollback(N/) 2>/dev/null | /usr/bin/wc -l | /usr/bin/tr -d ' ')" "1"

print -r -- ""
print -r -- "data the instance does not own is never purged"
ORIGINAL_PROFILE="$(config_field "$DIR" DOPPEL_PROFILE_ROOT)"
for guarded in "$HOME" "$HOME/Documents" "$HOME/.codex" "$HOME/Library/Application Support/Codex"; do
    set_profile_root "$DIR" "$guarded"
    run_real remove "$NAME" --purge-data
    [[ "$OUT" == *"refusing to purge"* ]] && pass "refuses to purge $guarded" \
        || fail "refuses to purge $guarded" "got: $OUT"
    [[ -d "$(app_path)" ]] || fail "  and removes nothing when it refuses" "$guarded: the app went anyway"
done
set_profile_root "$DIR" "$ORIGINAL_PROFILE"
check "the instance's own profile is purgeable again" \
    "$(protected_check=$(config_field "$DIR" DOPPEL_PROFILE_ROOT); print -r -- "${protected_check:t}")" "$NAME"

print -r -- ""
print -r -- "names that would become indistinguishable are refused"
/bin/mkdir -p "$DOPPEL_DIR/instances/$SIBLING_SLUG"
write_config_file "$DOPPEL_DIR/instances/$SIBLING_SLUG" "$SIBLING_NAME" \
    "com.openai.codex.doppel-$SIBLING_SLUG" "codex-$SIBLING_SLUG" \
    "$SCRATCH/sibling-profile" "$SCRATCH/sibling-codex" "EF4444"
run_real edit "$NAME" --rename "${SIBLING_NAME// /-}"
[[ "$OUT" == *"too close to"* ]] && pass "a rename that collides on the identifier is refused" \
    || fail "a rename that collides on the identifier is refused" "got: $OUT"
check "the instance kept its name" "$(config_field "$DIR" DOPPEL_DISPLAY_NAME)" "$NAME"
check "and the sibling is still reachable by its own name" \
    "$("$CLI" list --porcelain | /usr/bin/awk -F'\t' -v n="$SIBLING_NAME" '$2 == n {print $1}')" \
    "$SIBLING_SLUG"

print -r -- ""
print -r -- "a rename that cannot finish changes nothing at all"
/bin/mkdir -p "$APPS/Taken.app"
run_real edit "$NAME" --rename "Taken"
[[ "$OUT" == *"an app already exists"* ]] && pass "refused" || fail "refused" "got: $OUT"
check "the config was not renamed anyway" "$(config_field "$DIR" DOPPEL_DISPLAY_NAME)" "$NAME"
[[ -d "$(app_path)" ]] && pass "the bundle is still where the config says" \
    || fail "the bundle is still where the config says" "$(app_path) is gone"

print -r -- ""
print -r -- "a rename that does finish takes its pin with it"
OLD_APP="$(app_path)"
run_real edit "$NAME" --rename "$NAME Renamed"
NEW_APP="$(app_path)"
[[ "$NEW_APP" != "$OLD_APP" ]] && pass "the bundle moved" || fail "the bundle moved" "still at $OLD_APP"
[[ -s "$(pin_file "$NEW_APP")" ]] && pass "a pin is recorded for the new path" \
    || fail "a pin is recorded for the new path" "nothing at $(pin_file "$NEW_APP")"
[[ ! -e "$(pin_file "$OLD_APP")" ]] && pass "and the old one is not left behind" \
    || fail "and the old one is not left behind" "$(pin_file "$OLD_APP") survived"

print -r -- ""
print -r -- "an edit does not open an instance that was not running"
APP="$(app_path)"
/usr/bin/pgrep -f "${APP}/Contents/MacOS/" >/dev/null 2>&1 && \
    /usr/bin/osascript -e "tell application id \"com.openai.codex.doppel-$SLUG\" to quit" >/dev/null 2>&1
DOPPEL_RELAUNCH=1 "$CLI" edit "$NAME Renamed" --tint 84CC16 >/dev/null 2>&1
/bin/sleep 3
if /usr/bin/pgrep -f "${APP}/Contents/MacOS/" >/dev/null 2>&1; then
    fail "a closed instance stays closed" "the edit opened it"
    /usr/bin/osascript -e "tell application id \"com.openai.codex.doppel-$SLUG\" to quit" >/dev/null 2>&1
else
    pass "a closed instance stays closed"
fi

print -r -- ""
print -r -- "$PASSED passed, $FAILED failed"
(( FAILED == 0 ))
