#!/bin/zsh
# Opt-in local SSH integration QA for a disposable, already authenticated
# Remote Access fixture. This uses the release helper binary and the real sshd
# / ssh clients; it never copies credentials or deletes fixture data.
# First create/sign in to a temporary profile, then run:
# DOPPEL_REMOTE_QA_PROFILE='Remote QA Example' \
# DOPPEL_REMOTE_QA_DATA_ROOT='/private/tmp/doppel-remote-qa-data' \
# DOPPEL_REMOTE_QA_STAGE=prepare ./qa/remote-access.zsh
# Complete the isolated GUI sign-in, then rerun with DOPPEL_REMOTE_QA_STAGE=run.
set -euo pipefail
setopt PIPE_FAIL
zmodload zsh/datetime

readonly REPO_ROOT="${0:A:h:h}"
readonly CLI="$REPO_ROOT/bin/doppel"
readonly HELPER="${DOPPEL_REMOTE_QA_HELPER:-$REPO_ROOT/app/.build/release/DoppelRemoteHelper}"
readonly PROFILE="${DOPPEL_REMOTE_QA_PROFILE:-}"
readonly DATA_ROOT="${DOPPEL_REMOTE_QA_DATA_ROOT:-}"
readonly DOPPEL_HOME="${DOPPEL_HOME:-$HOME/Library/Application Support/Doppel}"
readonly INSTANCES_ROOT="$DOPPEL_HOME/instances"

fail() { print -u2 -r -- "FAIL $1"; exit 1; }
pass() { print -r -- "PASS $1"; }

[[ -n "$PROFILE" && "$PROFILE" == "Remote QA "* ]] || \
    fail "set DOPPEL_REMOTE_QA_PROFILE to the exact name of a disposable instance prefixed 'Remote QA '"
[[ -n "$DATA_ROOT" && -d "$DATA_ROOT" ]] || \
    fail "set DOPPEL_REMOTE_QA_DATA_ROOT to the existing temporary root for this disposable instance"
[[ -x "$CLI" && -x "$HELPER" ]] || fail "the checked-out CLI or built native helper is missing"

readonly REAL_DATA_ROOT="$(cd "$DATA_ROOT" && pwd -P)"
case "$REAL_DATA_ROOT/" in
    /private/tmp/*|/private/var/folders/*) ;;
    *) fail "the disposable profile data root must resolve inside a macOS temporary directory" ;;
esac

# Resolve by exact display name, then inspect only the generated instance
# configuration. The fixed slug is the routing key across a display rename.
readonly MATCH="$(/usr/bin/python3 - "$CLI" "$PROFILE" <<'PY'
import subprocess, sys
result = subprocess.run([sys.argv[1], "list", "--porcelain"], check=True,
                        stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)
matches = [line.split("\t") for line in result.stdout.splitlines()
           if len(line.split("\t")) >= 4 and line.split("\t")[1] == sys.argv[2]]
if len(matches) == 1:
    print(matches[0][0] + "\t" + matches[0][2] + "\t" + matches[0][3])
PY
)"
[[ -n "$MATCH" ]] || fail "the named disposable profile is not present in this DOPPEL_HOME"
IFS=$'\t' read -r SLUG APP_PATH APP_STATE <<< "$MATCH"
[[ "$SLUG" == remote-qa-* ]] || fail "the disposable profile slug must begin remote-qa-"
readonly PROFILE_DIR="$INSTANCES_ROOT/$SLUG"
[[ -r "$PROFILE_DIR/instance-config.zsh" ]] || fail "the disposable instance configuration is missing"

# These values are generated by Doppel and are used only for path checks and
# the native helper context. In particular, both data paths must remain under
# the explicitly supplied temporary root; pilot and live homes are refused.
source "$PROFILE_DIR/instance-config.zsh"
for path in "$DOPPEL_PROFILE_ROOT" "$DOPPEL_CODEX_HOME"; do
    [[ "$path" == /* && "$path" != *"/../"* ]] || fail "the disposable profile contains an unsafe data path"
    resolved="$(cd "$path" 2>/dev/null && pwd -P)" || fail "the disposable profile data path does not exist"
    [[ "$resolved" == "$REAL_DATA_ROOT"/* ]] || fail "the profile or CODEX_HOME is outside the supplied temporary root"
done
[[ -d "$APP_PATH" ]] || \
    fail "the disposable instance app path could not be confirmed"

typeset -g OWN_LISTENER=0 CONFLICT_PID="" ARTIFACTS=""
cleanup_owned_listener() {
    if [[ "$OWN_LISTENER" == 1 ]]; then
        "$HELPER" disable --profile-slug "$SLUG" --profile-dir "$PROFILE_DIR" \
            --desktop-home "$DOPPEL_CODEX_HOME" --primary-app "${DOPPEL_PRIMARY_APP:-/Applications/ChatGPT.app}" \
            --cli "$CLI" >/dev/null 2>&1 || true
        OWN_LISTENER=0
    fi
    if [[ -n "$CONFLICT_PID" ]] && kill -0 "$CONFLICT_PID" 2>/dev/null; then
        kill "$CONFLICT_PID" 2>/dev/null || true
        wait "$CONFLICT_PID" 2>/dev/null || true
    fi
}
trap cleanup_owned_listener EXIT INT TERM

helper() {
    local command="$1"; shift
    "$HELPER" "$command" --profile-slug "$SLUG" --profile-dir "$PROFILE_DIR" \
        --desktop-home "$DOPPEL_CODEX_HOME" --primary-app "${DOPPEL_PRIMARY_APP:-/Applications/ChatGPT.app}" \
        --cli "$CLI" "$@"
}

status_json() {
    local timeout="${1:-8}"
    /usr/bin/python3 - "$HELPER" "$SLUG" "$PROFILE_DIR" "$DOPPEL_CODEX_HOME" \
        "${DOPPEL_PRIMARY_APP:-/Applications/ChatGPT.app}" "$CLI" "$timeout" <<'PY'
import subprocess, sys
helper, slug, profile_dir, desktop_home, primary_app, cli, timeout = sys.argv[1:]
args = [helper, "status", "--profile-slug", slug, "--profile-dir", profile_dir,
        "--desktop-home", desktop_home, "--primary-app", primary_app, "--cli", cli]
try:
    result = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                            timeout=float(timeout), check=False)
except subprocess.TimeoutExpired:
    sys.exit(124)
if result.returncode:
    sys.exit(result.returncode)
sys.stdout.buffer.write(result.stdout)
PY
}

load_status() {
    local json fields timeout="${1:-8}"
    json="$(status_json "$timeout")" || return 1
    fields="$(print -r -- "$json" | /usr/bin/python3 -c 'import json,sys; d=json.load(sys.stdin); keys=("state","enabled","remoteId","host","bindAddress","port","username","email","accountId","hostKeyFingerprint","checkedAt"); value=lambda k: ("true" if d[k] is True else "false") if isinstance(d.get(k),bool) else ("" if d.get(k) is None else str(d[k])); print("\x1f".join(value(k) for k in keys))')" \
        || return 1
    IFS=$'\x1f' read -r STATE ENABLED REMOTE_ID HOST BIND PORT USERNAME EMAIL ACCOUNT_ID HOST_FINGERPRINT CHECKED_AT <<< "$fields"
}

await_ready() {
    local deadline="$(( EPOCHREALTIME + 8.0 ))" remaining
    while (( EPOCHREALTIME < deadline )); do
        remaining="$(( deadline - EPOCHREALTIME ))"
        if load_status "$remaining" && [[ "$ENABLED" == true && "$STATE" == ready ]]; then
            return 0
        fi
        sleep 0.2
    done
    return 1
}

if [[ "$APP_STATE" != installed || ! -d "$APP_PATH" ]]; then
    fail "the disposable profile needs its installed app bundle for the rename and removal checks"
fi

load_status || fail "native helper status failed"
if [[ -z "$REMOTE_ID" ]]; then
    # Configure only the named throwaway profile on an address reported by the
    # native helper. No listener is enabled by this preparation step.
    NETWORKS="$(print -r -- "$(status_json)" | /usr/bin/python3 -c 'import json,sys; d=json.load(sys.stdin); print("\n".join(x["address"] for x in d.get("networks",[]) if x.get("address")))')" \
        || fail "could not inspect private network addresses"
    ADDRESS="${NETWORKS[(f)1]:-}"
    [[ -n "$ADDRESS" ]] || fail "no private IPv4 address is currently available"
    helper configure --bind-address "$ADDRESS" --host "$ADDRESS" >/dev/null 2>&1 \
        || fail "could not configure the isolated fixture on its current private address"
    pass "isolated profile configured without starting a listener"
    load_status || fail "native helper status failed after configure"
fi

[[ "$ENABLED" != true ]] || fail "the fixture was already enabled; refusing to take ownership of its listener"
if [[ "${DOPPEL_REMOTE_QA_STAGE:-run}" == prepare ]]; then
    pass "isolated fixture is configured; finish its GUI sign-in, then rerun with DOPPEL_REMOTE_QA_STAGE=run"
    exit 0
fi
[[ "${DOPPEL_REMOTE_QA_STAGE:-run}" == run ]] || fail "DOPPEL_REMOTE_QA_STAGE must be prepare or run"
[[ "$STATE" == disabled && -n "$CHECKED_AT" && -n "$EMAIL" && -n "$ACCOUNT_ID" ]] || \
    fail "the isolated remote runtime needs its own GUI sign-in before live SSH QA can run"

# Reject shell quoting/injection payloads at the helper boundary. The supplied
# argument contains spaces and shell metacharacters, but is passed as one argv
# element and must not create the marker file.
ARTIFACTS="$(/usr/bin/mktemp -d "${TMPDIR%/}/doppel-remote-qa.XXXXXXXX")"
/bin/chmod 700 "$ARTIFACTS"
MARKER="$ARTIFACTS/should-not-exist"
BAD_HOST="invalid.example'; touch '$MARKER"
if helper configure --bind-address "$BIND" --host "$BAD_HOST" >/dev/null 2>&1 || [[ -e "$MARKER" ]]; then
    fail "quoted invalid host was not rejected safely"
fi
pass "quoted arguments are validated without shell execution"

# A new per-profile key is created only inside this explicit disposable remote
# configuration. The account identifiers remain process-local and are never
# printed; there is no authentication/key copying in this script.
if ! ENABLE_RESULT="$(helper enable --expected-account-id "$ACCOUNT_ID" --expected-email "$EMAIL" 2>/dev/null)"; then
    fail "native helper could not enable the isolated listener; check the disposable runtime and GUI sign-in"
fi
OWN_LISTENER=1
print -r -- "$ENABLE_RESULT" | /usr/bin/python3 -c 'import json,sys; d=json.load(sys.stdin); assert d.get("enabled") is True and d.get("state")=="ready"' \
    || fail "enable returned before its listener was ready"
pass "enable returns actual listener readiness without a later refresh"
await_ready || fail "listener did not become ready within eight seconds after enable"
[[ "$REMOTE_ID" != "" ]] || fail "listener status omitted its remote identifier"
readonly ORIGINAL_ID="$REMOTE_ID" ORIGINAL_PORT="$PORT" ORIGINAL_HOST="$HOST" ORIGINAL_BIND="$BIND" \
    ORIGINAL_USER="$USERNAME" ORIGINAL_FP="$HOST_FINGERPRINT"
[[ -n "$ORIGINAL_FP" ]] || fail "the helper did not report a host-key fingerprint"

readonly REMOTE_DIR="$HOME/.dpr/$ORIGINAL_ID"
readonly LISTENER_PID_FILE="$REMOTE_DIR/sshd.pid"
[[ -r "$REMOTE_DIR/client-key.pem" && -r "$LISTENER_PID_FILE" ]] || fail "the isolated listener key or PID record is missing"
readonly CLIENT_KEY="$REMOTE_DIR/client-key.pem"
readonly PID="$(<"$LISTENER_PID_FILE")"
[[ "$PID" == <1-> ]] || fail "the isolated listener PID record is invalid"

# Verify the actual sshd process owns exactly the selected private IPv4
# listener. This catches wildcard and loopback binds independently of status.
SOCKETS="$(/usr/sbin/lsof -nP -a -p "$PID" -iTCP -sTCP:LISTEN -Fn 2>/dev/null | /usr/bin/sed -n 's/^n//p')" \
    || fail "could not inspect the isolated sshd listener"
[[ "$SOCKETS" == "$ORIGINAL_BIND:$ORIGINAL_PORT" ]] || fail "sshd is not bound only to the selected private address"
pass "listener binds only to the selected private address"

# Pin the host key read from this local listener and require it to match the
# helper's fingerprint before any authenticated command is sent.
KNOWN_HOSTS="$ARTIFACTS/known_hosts"
/usr/bin/ssh-keyscan -T 5 -t ed25519 -p "$ORIGINAL_PORT" "$ORIGINAL_HOST" > "$KNOWN_HOSTS" 2>/dev/null \
    || fail "could not read the local listener host key"
SCANNED_FP="$(/usr/bin/ssh-keygen -lf "$KNOWN_HOSTS" -E sha256 2>/dev/null | /usr/bin/awk 'NR==1 {print $2}')"
[[ -n "$SCANNED_FP" && "$SCANNED_FP" == "$ORIGINAL_FP" ]] || fail "the live host key does not match the helper status fingerprint"
SSH_OPTIONS=(-F /dev/null -i "$CLIENT_KEY" -p "$ORIGINAL_PORT" -o BatchMode=yes -o IdentitiesOnly=yes \
    -o ProxyCommand=none -o ProxyJump=none \
    -o StrictHostKeyChecking=yes -o "UserKnownHostsFile=$KNOWN_HOSTS" -o ConnectTimeout=5)
TARGET="$ORIGINAL_USER@$ORIGINAL_HOST"

# Preserve real remote-shell argument quoting and exit status end-to-end.
set +e
SSH_OUTPUT="$(/usr/bin/ssh "${SSH_OPTIONS[@]}" "$TARGET" "printf '%s' 'quoted QA argument'; exit 37" 2>/dev/null)"
SSH_STATUS=$?
set -e
[[ "$SSH_STATUS" == 37 && "$SSH_OUTPUT" == "quoted QA argument" ]] || fail "SSH did not preserve a quoted command and its exit status 37"
pass "SSH preserves quoted arguments and remote exit status 37"

# Empty original commands must be refused by the production forced-command
# helper, and an unrelated key must never authenticate.
if /usr/bin/ssh "${SSH_OPTIONS[@]}" "$TARGET" </dev/null >/dev/null 2>&1; then
    fail "an empty SSH command was accepted"
fi
/usr/bin/ssh-keygen -q -t ecdsa -b 256 -N '' -f "$ARTIFACTS/wrong-key" >/dev/null 2>&1 \
    || fail "could not create the disposable wrong-key fixture"
if /usr/bin/ssh -F /dev/null -i "$ARTIFACTS/wrong-key" -p "$ORIGINAL_PORT" -o BatchMode=yes \
    -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -o "UserKnownHostsFile=$KNOWN_HOSTS" \
    -o ConnectTimeout=5 "$TARGET" "printf wrong-key-accepted" >/dev/null 2>&1; then
    fail "an unrelated SSH key was accepted"
fi
pass "empty commands and unrelated keys are rejected"

if /usr/bin/nc -z -G 2 127.0.0.1 "$ORIGINAL_PORT" >/dev/null 2>&1; then
    fail "listener is reachable through loopback instead of only the selected private address"
fi
pass "listener is not exposed on loopback"

# Disable and re-enable through the same helper, then verify endpoint and host
# identity stability before exercising a port conflict.
helper disable >/dev/null 2>&1 || fail "disable failed"
OWN_LISTENER=0
load_status || fail "status failed after disable"
[[ "$ENABLED" == false ]] || fail "disable left the profile enabled"
if /usr/bin/nc -z -G 2 "$ORIGINAL_HOST" "$ORIGINAL_PORT" >/dev/null 2>&1; then
    fail "the listener still accepts connections after disable"
fi
helper enable --expected-account-id "$ACCOUNT_ID" --expected-email "$EMAIL" >/dev/null 2>&1 \
    || fail "re-enable failed for the same isolated identity"
OWN_LISTENER=1
await_ready || fail "listener did not become ready within eight seconds after re-enable"
[[ "$PORT" == "$ORIGINAL_PORT" && "$HOST" == "$ORIGINAL_HOST" && "$HOST_FINGERPRINT" == "$ORIGINAL_FP" ]] \
    || fail "re-enable changed the private endpoint or host identity"
pass "disable revokes access and re-enable preserves the endpoint"

# Stop only our listener, occupy only its configured address/port with a test
# process, and prove that enable fails without changing the configured port.
helper disable >/dev/null 2>&1 || fail "disable before port-conflict check failed"
OWN_LISTENER=0
/usr/bin/python3 - "$ORIGINAL_BIND" "$ORIGINAL_PORT" <<'PY' >/dev/null 2>&1 &
import socket, sys, time
s = socket.socket()
s.bind((sys.argv[1], int(sys.argv[2])))
s.listen(1)
while True:
    time.sleep(60)
PY
CONFLICT_PID=$!
sleep 0.2
kill -0 "$CONFLICT_PID" 2>/dev/null || fail "could not start the owned port-conflict fixture"
if helper enable --expected-account-id "$ACCOUNT_ID" --expected-email "$EMAIL" >/dev/null 2>&1; then
    fail "enable accepted an occupied listener port"
fi
load_status || fail "status failed after the occupied-port check"
[[ "$PORT" == "$ORIGINAL_PORT" && "$ENABLED" == false ]] || fail "port conflict changed configuration or enabled state"
kill "$CONFLICT_PID" 2>/dev/null || true
wait "$CONFLICT_PID" 2>/dev/null || true
CONFLICT_PID=""
pass "port conflict fails closed without changing the endpoint"

helper enable --expected-account-id "$ACCOUNT_ID" --expected-email "$EMAIL" >/dev/null 2>&1 \
    || fail "listener did not recover after the port was released"
OWN_LISTENER=1
await_ready || fail "listener did not recover within eight seconds after releasing its port"
[[ "$HOST_FINGERPRINT" == "$ORIGINAL_FP" && "$PORT" == "$ORIGINAL_PORT" ]] || fail "recovery changed the host identity"

# A display rename must continue to route status to the same remoteId/port.
# It touches only the explicitly disposable instance; Doppel keeps the original
# slug as its routing key. Removal is the final step and moves the app/profile
# definition to the normal reversible Trash/Removed locations. The .dpr home
# and credentials are intentionally preserved.
readonly RENAMED_PROFILE="Remote QA ${SLUG} Renamed"
(( ${#RENAMED_PROFILE} <= 64 )) || fail "the disposable profile slug is too long for the rename-routing check"
DOPPEL_DEV=1 DOPPEL_RELAUNCH=0 DOPPEL_NO_ALERT=1 "$CLI" edit "$PROFILE" --rename "$RENAMED_PROFILE" \
    >/dev/null 2>&1 || fail "the disposable instance could not be renamed"
RENAMED_STATUS="$(DOPPEL_DEV=1 "$CLI" remote status "$RENAMED_PROFILE" --json 2>/dev/null)" \
    || fail "remote status did not route through the renamed profile"
print -r -- "$RENAMED_STATUS" | /usr/bin/python3 -c 'import json,sys; d=json.load(sys.stdin); assert d.get("remoteId")==sys.argv[1] and str(d.get("port"))==sys.argv[2]' "$ORIGINAL_ID" "$ORIGINAL_PORT" \
    || fail "renamed profile status did not retain its remote configuration"
pass "renamed profile routes to the same remote configuration"

DOPPEL_DEV=1 DOPPEL_RELAUNCH=0 DOPPEL_NO_ALERT=1 "$CLI" remove "$RENAMED_PROFILE" \
    >/dev/null 2>&1 || fail "profile removal did not complete its remote revocation"
OWN_LISTENER=0
if /usr/bin/nc -z -G 2 "$ORIGINAL_HOST" "$ORIGINAL_PORT" >/dev/null 2>&1; then
    fail "profile removal left the remote listener reachable"
fi
pass "profile removal revokes SSH access and preserves remote data"
print -r -- "Remote Access QA passed. Private test artifacts retained at $ARTIFACTS"
